import { StyleSheet } from 'react-native';

export const COLORS = {
  accent: '#3b82f6',
  bg: '#edf3fb',
  border: '#d8e3f0',
  card: '#ffffff',
  danger: '#ef4444',
  muted: '#627285',
  success: '#10b981',
  text: '#0e1a2f',
};

export const styles = StyleSheet.create({
  actionCircle: {
    alignItems: 'center',
    backgroundColor: COLORS.card,
    borderColor: COLORS.border,
    borderRadius: 999,
    borderWidth: 1,
    height: 120,
    justifyContent: 'center',
    marginHorizontal: 8,
    width: 120,
  },
  actionCircleLabel: {
    color: COLORS.text,
    fontSize: 13,
    fontWeight: '600',
    marginTop: 8,
    textAlign: 'center',
  },
  actionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'center',
    marginVertical: 20,
  },
  backButton: {
    alignSelf: 'flex-start',
    marginBottom: 12,
    paddingVertical: 4,
  },
  backLabel: {
    color: COLORS.accent,
    fontSize: 14,
    fontWeight: '600',
  },
  card: {
    backgroundColor: COLORS.card,
    borderColor: COLORS.border,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 10,
    padding: 14,
  },
  cardMuted: {
    color: COLORS.muted,
    fontSize: 13,
    marginTop: 4,
  },
  cardTitle: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: '700',
  },
  chip: {
    backgroundColor: '#e8f0fe',
    borderRadius: 999,
    marginRight: 8,
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  chipActive: {
    backgroundColor: COLORS.accent,
  },
  chipLabel: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '600',
  },
  chipLabelActive: {
    color: '#ffffff',
  },
  column: {
    backgroundColor: COLORS.card,
    borderColor: COLORS.border,
    borderRadius: 12,
    borderWidth: 1,
    marginRight: 12,
    minHeight: 200,
    minWidth: 200,
    padding: 10,
  },
  columnTitle: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 8,
  },
  container: {
    backgroundColor: COLORS.bg,
    flex: 1,
    minHeight: '100%',
    padding: 20,
  },
  ctaButton: {
    alignItems: 'center',
    backgroundColor: COLORS.accent,
    borderRadius: 10,
    marginTop: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  ctaLabel: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  empty: {
    color: COLORS.muted,
    fontSize: 14,
    paddingVertical: 24,
    textAlign: 'center',
  },
  field: {
    backgroundColor: COLORS.card,
    borderColor: COLORS.border,
    borderRadius: 8,
    borderWidth: 1,
    color: COLORS.text,
    fontSize: 14,
    marginBottom: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  fieldLabel: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 4,
  },
  header: {
    marginBottom: 8,
  },
  headerSubtitle: {
    color: COLORS.muted,
    fontSize: 14,
    marginTop: 4,
  },
  headerTitle: {
    color: COLORS.text,
    fontSize: 24,
    fontWeight: '800',
  },
  horizontalScroll: {
    flexDirection: 'row',
    gap: 12,
    paddingBottom: 8,
  },
  iconCircle: {
    alignItems: 'center',
    backgroundColor: '#e8f0fe',
    borderRadius: 999,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  listItem: {
    backgroundColor: COLORS.card,
    borderColor: COLORS.border,
    borderRadius: 10,
    borderWidth: 1,
    marginBottom: 8,
    padding: 12,
  },
  macroBar: {
    backgroundColor: '#e8f0fe',
    borderRadius: 8,
    flex: 1,
    marginHorizontal: 4,
    padding: 10,
  },
  macroLabel: {
    color: COLORS.muted,
    fontSize: 11,
    fontWeight: '600',
  },
  macroRow: {
    flexDirection: 'row',
    marginTop: 12,
  },
  macroValue: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: '700',
    marginTop: 4,
  },
  modalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(14, 26, 47, 0.45)',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    padding: 20,
    position: 'fixed' as unknown as 'absolute',
    right: 0,
    top: 0,
    zIndex: 50,
  },
  modalCard: {
    backgroundColor: COLORS.card,
    borderRadius: 14,
    maxHeight: '85%',
    maxWidth: 560,
    padding: 20,
    width: '100%',
  },
  rowBetween: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  searchCard: {
    backgroundColor: COLORS.card,
    borderColor: COLORS.border,
    borderRadius: 12,
    borderWidth: 1,
    marginTop: 16,
    padding: 14,
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#e8f0fe',
    borderRadius: 10,
    marginTop: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  secondaryLabel: {
    color: COLORS.accent,
    fontSize: 13,
    fontWeight: '700',
  },
  sectionTitle: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 8,
    marginTop: 16,
  },
});
