export const formStyles = {
  chip: {
    alignItems: 'center',
    backgroundColor: '#eff6ff',
    borderColor: '#bfdbfe',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  chipLabel: {
    color: '#1d4ed8',
    fontSize: 12,
    fontWeight: '700',
  },
  chipRemove: {
    color: '#1e3a8a',
    fontSize: 12,
    fontWeight: '700',
  },
  input: {
    backgroundColor: '#f8fafc',
    borderColor: '#d1dbe8',
    borderRadius: 10,
    borderWidth: 1,
    color: '#0f172a',
    fontSize: 13,
    minHeight: 38,
    paddingHorizontal: 10,
  },
  selectInput: {
    backgroundColor: '#f8fafc',
    borderColor: '#d1dbe8',
    borderRadius: 10,
    borderWidth: 1,
    color: '#0f172a',
    fontSize: 13,
    minHeight: 38,
    padding: 8,
  },
  flexInput: {
    flex: 1,
    minWidth: 260,
  },
  textArea: {
    minHeight: 92,
    paddingTop: 8,
    textAlignVertical: 'top',
  },
  inputReadonly: {
    backgroundColor: '#f8fafc',
    color: '#64748b',
  },
  inputEditable: {
    backgroundColor: '#ffffff',
    borderColor: '#1c74e9',
    borderWidth: 2,
  },
  actionButton: {
    alignItems: 'center',
    backgroundColor: '#1c74e9',
    borderRadius: 10,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 14,
  },
  actionLabel: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#eff6ff',
    borderColor: '#bfdbfe',
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 12,
  },
  secondaryLabel: {
    color: '#1d4ed8',
    fontSize: 12,
    fontWeight: '700',
  },
  dangerButton: {
    alignItems: 'center',
    backgroundColor: '#fee2e2',
    borderColor: '#fecaca',
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 12,
  },
  dangerLabel: {
    color: '#b91c1c',
    fontSize: 12,
    fontWeight: '700',
  },
} as const;
