import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  actionsColumn: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'flex-end',
  },
  arrow: {
    color: '#8a98ab',
    fontSize: 18,
    fontWeight: '700',
  },
  assignButton: {
    alignItems: 'center',
    backgroundColor: '#eff5ff',
    borderColor: '#d3e3ff',
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 12,
  },
  assignLabel: {
    color: '#1c58b4',
    fontSize: 12,
    fontWeight: '800',
  },
  avatarFallback: {
    alignItems: 'center',
    backgroundColor: '#edf3fd',
    borderColor: '#d2dff2',
    borderRadius: 24,
    borderWidth: 1,
    height: 96,
    justifyContent: 'center',
    width: 96,
  },
  avatarFallbackLabel: {
    color: '#3c506b',
    fontSize: 14,
    fontWeight: '800',
  },
  avatarImage: {
    borderRadius: 24,
    height: 96,
    width: 96,
  },
  detailCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#dce5f2',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 76,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  detailIcon: {
    alignItems: 'center',
    backgroundColor: '#edf4ff',
    borderRadius: 10,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  detailIconLabel: {
    fontSize: 18,
  },
  detailLeft: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  detailSubtitle: {
    color: '#5f6f84',
    fontSize: 12,
  },
  detailText: {
    gap: 2,
  },
  detailTitle: {
    color: '#131b2a',
    fontSize: 14,
    fontWeight: '800',
  },
  kpiCard: {
    backgroundColor: '#ffffff',
    borderColor: '#dce5f2',
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    gap: 8,
    minHeight: 82,
    minWidth: 210,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  kpiCardsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  kpiCardTitle: {
    color: '#8b96a6',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  kpiCardValue: {
    color: '#1c2f50',
    fontSize: 30,
    fontWeight: '800',
  },
  detailsWrap: {
    gap: 8,
  },
  empty: {
    color: '#607289',
    fontSize: 14,
  },
  identityColumn: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 14,
  },
  identityText: {
    flex: 1,
    gap: 5,
  },
  name: {
    color: '#111827',
    fontSize: 24,
    fontWeight: '800',
  },
  objective: {
    color: '#1a5bb3',
    fontSize: 14,
    fontWeight: '700',
  },
  page: {
    gap: 10,
  },
  primaryAction: {
    alignItems: 'center',
    backgroundColor: '#f3f6fb',
    borderColor: '#d7e2f1',
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 12,
  },
  primaryActionLabel: {
    color: '#314c73',
    fontSize: 12,
    fontWeight: '800',
  },
  secondaryAction: {
    alignItems: 'center',
    backgroundColor: '#1c74e9',
    borderRadius: 10,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 12,
  },
  secondaryActionLabel: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
  },
  statPill: {
    backgroundColor: '#f3f7fd',
    borderColor: '#dce6f4',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  statPillLabel: {
    color: '#455a75',
    fontSize: 12,
    fontWeight: '700',
  },
  statsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  success: {
    color: '#1f7a45',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 8,
  },
  summaryCard: {
    backgroundColor: '#ffffff',
    borderColor: '#dce5f2',
    borderRadius: 16,
    borderWidth: 1,
    padding: 14,
  },
  summaryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'space-between',
  },
});
