import { StyleSheet } from 'react-native';

const COLORS = {
  action: '#1c74e9',
  bg: '#f0f2f5',
  border: '#dfe8f5',
  card: '#ffffff',
  text: '#111418',
  textMuted: '#6a7381',
  white: '#ffffff',
};

export const styles = StyleSheet.create({
  backButton: {
    alignItems: 'center',
    backgroundColor: '#eff4ff',
    borderColor: '#d4e2f5',
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 10,
  },
  backLabel: {
    color: '#2f4f7d',
    fontSize: 12,
    fontWeight: '700',
  },
  badge: {
    backgroundColor: '#eef4ff',
    borderColor: '#d6e4ff',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  badgeText: {
    color: '#214c9f',
    fontSize: 12,
    fontWeight: '700',
  },
  breadcrumb: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '700',
  },
  breadcrumbCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#dfe8f5',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    width: '100%',
  },
  container: {
    gap: 12,
    maxWidth: 1280,
    width: '100%',
  },
  createButton: {
    alignItems: 'center',
    backgroundColor: COLORS.action,
    borderRadius: 12,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 36,
    shadowColor: '#1d4ed8',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
  },
  createLabel: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '800',
  },
  ctaCard: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'space-between',
  },
  ctaSubtitle: {
    color: '#64748b',
    fontSize: 14,
    lineHeight: 21,
  },
  ctaText: {
    flex: 1,
    gap: 4,
    maxWidth: 760,
  },
  ctaTitle: {
    color: COLORS.text,
    fontSize: 30,
    fontWeight: '800',
  },
  empty: {
    color: COLORS.textMuted,
    fontSize: 14,
  },
  formCard: {
    backgroundColor: '#f4f7fc',
    borderColor: '#e5ecf7',
    borderRadius: 16,
    borderWidth: 1,
    padding: 22,
    width: '100%',
  },
  hero: {
    backgroundColor: COLORS.card,
    borderColor: COLORS.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 8,
    padding: 16,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.06,
    shadowRadius: 18,
  },
  listCard: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
    padding: 0,
    width: '100%',
  },
  managementButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#0f172a',
    borderRadius: 10,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 14,
  },
  managementButtonLabel: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
  },
  managementCard: {
    backgroundColor: '#ffffff',
    borderColor: '#dfe8f5',
    borderRadius: 20,
    borderWidth: 1,
    gap: 10,
    paddingHorizontal: 18,
    paddingVertical: 16,
    width: '100%',
  },
  managementSubtitle: {
    color: '#64748b',
    fontSize: 13,
    fontWeight: '600',
  },
  managementSummary: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  managementSummaryText: {
    backgroundColor: '#eff6ff',
    borderColor: '#dbeafe',
    borderRadius: 999,
    borderWidth: 1,
    color: '#1d4ed8',
    fontSize: 12,
    fontWeight: '700',
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  managementTitle: {
    color: '#0f172a',
    fontSize: 22,
    fontWeight: '800',
  },
  page: {
    alignItems: 'center',
    backgroundColor: COLORS.bg,
    flexGrow: 1,
    paddingHorizontal: 28,
    paddingVertical: 24,
  },
  profileCard: {
    backgroundColor: COLORS.card,
    borderColor: COLORS.border,
    borderRadius: 14,
    borderWidth: 1,
    minHeight: 240,
    padding: 14,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
    width: '100%',
  },
  subtitle: {
    color: COLORS.textMuted,
    fontSize: 13,
  },
  title: {
    color: COLORS.text,
    fontSize: 25,
    fontWeight: '800',
  },
});
