import { StyleSheet } from 'react-native';

const COLORS = {
  action: '#1c74e9',
  bg: '#eef3fb',
  border: '#dfe8f5',
  card: '#ffffff',
  text: '#111418',
  textMuted: '#6a7381',
  white: '#ffffff',
};

export const styles = StyleSheet.create({
  badge: {
    backgroundColor: '#eef4ff',
    borderColor: '#d6e4ff',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  badgeText: {
    color: '#214c9f',
    fontSize: 12,
    fontWeight: '700',
  },
  container: {
    gap: 12,
    maxWidth: 980,
    width: '100%',
  },
  createButton: {
    alignItems: 'center',
    backgroundColor: COLORS.action,
    borderRadius: 12,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 20,
  },
  createLabel: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '800',
  },
  ctaCard: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  ctaSubtitle: {
    color: COLORS.textMuted,
    fontSize: 14,
  },
  ctaText: {
    flex: 1,
    gap: 4,
    maxWidth: 640,
  },
  ctaTitle: {
    color: COLORS.text,
    fontSize: 24,
    fontWeight: '800',
  },
  empty: {
    color: COLORS.textMuted,
    fontSize: 14,
  },
  formCard: {
    backgroundColor: COLORS.card,
    borderColor: COLORS.border,
    borderRadius: 14,
    borderWidth: 1,
    padding: 14,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    width: '100%',
  },
  hero: {
    backgroundColor: COLORS.card,
    borderColor: COLORS.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 8,
    padding: 16,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.06,
    shadowRadius: 18,
  },
  listCard: {
    backgroundColor: COLORS.card,
    borderColor: COLORS.border,
    borderRadius: 14,
    borderWidth: 1,
    padding: 14,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
    width: '100%',
  },
  page: {
    alignItems: 'center',
    backgroundColor: COLORS.bg,
    flexGrow: 1,
    padding: 22,
  },
  profileCard: {
    backgroundColor: COLORS.card,
    borderColor: COLORS.border,
    borderRadius: 14,
    borderWidth: 1,
    minHeight: 240,
    padding: 14,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
    width: '100%',
  },
  subtitle: {
    color: COLORS.textMuted,
    fontSize: 13,
  },
  title: {
    color: COLORS.text,
    fontSize: 25,
    fontWeight: '800',
  },
});
