import { StyleSheet } from 'react-native';

export const C = {
  bg: '#f8fafc',
  card: '#ffffff',
  text: '#0f172a',
  muted: '#64748b',
  border: '#e2e8f0',
  blue: '#3b82f6',
  dot: '#f59e0b',
  white: '#ffffff',
};

export const ss = StyleSheet.create({
  container: { padding: 24, gap: 20, backgroundColor: C.bg, minHeight: '100%' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  title: { fontSize: 24, fontWeight: '700', color: C.text },
  headerRight: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  searchContainer: {
    alignItems: 'center',
    backgroundColor: C.card,
    borderColor: C.border,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    width: 240,
  },
  searchInput: { color: C.text, flex: 1, fontSize: 13, outlineStyle: 'none' } as object,
  createBtn: {
    alignItems: 'center',
    backgroundColor: C.blue,
    borderRadius: 10,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  createBtnText: { color: C.white, fontWeight: '600', fontSize: 13 },
  tabRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: C.border },
  tab: { paddingHorizontal: 16, paddingVertical: 10 },
  tabActive: { borderBottomWidth: 2, borderBottomColor: C.blue },
  tabText: { fontSize: 14, fontWeight: '600', color: C.muted },
  tabTextActive: { color: C.blue },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 24 },
  empty: { color: C.muted, fontSize: 14, marginTop: 8 },
  card: {
    width: 'calc(25% - 18px)' as unknown as number,
    backgroundColor: C.card,
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
  },
  cardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: C.dot },
  iconBtn: { padding: 4 },
  cardImg: {
    height: 160,
    width: '100%',
    backgroundColor: '#0f172a',
    overflow: 'hidden',
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imgBackdrop: { ...StyleSheet.absoluteFillObject },
  imgShade: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(7,12,20,0.2)' },
  imgInner: {
    width: '100%',
    height: '100%',
    transitionProperty: 'transform',
    transitionDuration: '0.3s',
    transitionTimingFunction: 'ease-in-out',
  } as object,
  imgInnerHovered: { transform: [{ scale: 1.12 }] },
  cardBody: { padding: 12, gap: 6 },
  cardName: { fontSize: 15, fontWeight: '700', color: C.text },
  cardMeta: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  cardMetaBlue: { fontSize: 12, fontWeight: '600', color: C.blue },
  cardMetaGray: { fontSize: 12, color: C.muted },
});
