import { StyleSheet } from 'react-native';

export const s = StyleSheet.create({
  page: { padding: 24, gap: 16 },
  title: { fontSize: 22, fontWeight: '700', color: '#1e293b' },
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    gap: 12,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  label: { fontSize: 16, fontWeight: '700', color: '#1e293b', marginBottom: 8 },
  input: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    padding: 10,
    fontSize: 14,
    color: '#1e293b',
  },
  inputReadOnly: {
    backgroundColor: '#f8fafc',
  },
  objectiveSectionHeader: { gap: 4 },
  objectiveSectionTitle: { fontSize: 16, fontWeight: '700', color: '#1e293b' },
  objectiveSectionSubtitle: { fontSize: 12, color: '#94a3b8' },
  objectiveSelectLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748b',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  objectiveDropdownTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    padding: 12,
    backgroundColor: '#f8fafc',
  },
  objectiveDropdownIcon: { fontSize: 16, color: '#94a3b8' },
  objectiveDropdownPlaceholder: { flex: 1, fontSize: 13, color: '#94a3b8' },
  objectiveDropdownChevron: { fontSize: 10, color: '#94a3b8' },
  objectiveDropdownList: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  objectiveDropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  objectiveDropdownDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#cbd5e1',
  },
  objectiveDropdownDotSelected: { backgroundColor: '#3b82f6' },
  objectiveDropdownItemText: { fontSize: 13, color: '#64748b' },
  objectiveDropdownItemTextSelected: { color: '#1d4ed8', fontWeight: '700' },
  objectiveChipsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  objectiveSelectedChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#dbeafe',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#93c5fd',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  objectiveSelectedChipText: { fontSize: 12, fontWeight: '700', color: '#1d4ed8' },
  objectiveSelectedChipRemove: { fontSize: 16, color: '#3b82f6', lineHeight: 18 },
  objectiveAddMore: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#93c5fd',
  },
  objectiveAddMoreText: { fontSize: 12, fontWeight: '700', color: '#3b82f6' },
  objectiveChipDisabled: {
    opacity: 0.55,
  },
  successBanner: { backgroundColor: '#dcfce7', borderRadius: 8, padding: 12 },
  successText: { color: '#166534', fontWeight: '600', textAlign: 'center' },

  // Day tabs
  dayTabRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  dayTab: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#f1f5f9',
  },
  dayTabActive: { backgroundColor: '#3b82f6' },
  dayTabText: { fontSize: 13, fontWeight: '500', color: '#64748b' },
  dayTabTextActive: { color: '#fff' },
  addDayBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderStyle: 'dashed',
  },
  addDayText: { fontSize: 13, color: '#3b82f6', fontWeight: '500' },

  // Day header
  dayHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  deleteDayBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: '#fee2e2',
  },
  deleteDayText: { fontSize: 12, color: '#dc2626', fontWeight: '500' },

  // Block card
  blockCard: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  blockHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  dragHandle: { fontSize: 20, color: '#94a3b8', paddingRight: 4 },
  blockName: { flex: 1, fontSize: 14, fontWeight: '700', color: '#1e293b' },
  blockTag: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: '#f1f5f9',
  },
  blockTagText: { fontSize: 11, fontWeight: '600', color: '#64748b', textTransform: 'capitalize' },
  blockActions: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  viewDetailBtn: { padding: 8, borderRadius: 8, backgroundColor: '#f1f5f9' },
  viewDetailBtnText: { fontSize: 14 },
  moveBtn: { padding: 4, paddingHorizontal: 8, borderRadius: 4, backgroundColor: '#e2e8f0' },
  moveBtnText: { fontSize: 11, color: '#475569', fontWeight: '500' },
  removeBtn: { padding: 8, borderRadius: 8, backgroundColor: '#fee2e2' },
  removeBtnText: { color: '#dc2626', fontWeight: '700', fontSize: 12 },
  blockFields: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },

  // Number field
  numberField: { gap: 4, minWidth: 80 },
  numberLabel: { fontSize: 11, fontWeight: '500', color: '#64748b' },
  numberInput: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 6,
    padding: 6,
    fontSize: 13,
    width: 80,
    textAlign: 'center',
  },

  // Add block
  addBlockBtn: {
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#cbd5e1',
  },
  addBlockText: { fontSize: 13, color: '#3b82f6', fontWeight: '500' },
  blockTypeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  blockTypeBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#3b82f6',
  },
  blockTypeBtnText: { color: '#fff', fontSize: 12, fontWeight: '600' },

  // Save
  saveBtn: {
    backgroundColor: '#3b82f6',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
  },
  saveBtnText: { color: '#fff', fontWeight: '700', fontSize: 15 },

  // Template list
  templateItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  templateName: { fontSize: 14, fontWeight: '600', color: '#1e293b' },
  templateMeta: { fontSize: 12, color: '#94a3b8' },
  templateBadge: {
    fontSize: 10,
    fontWeight: '700',
    color: '#fff',
    backgroundColor: '#94a3b8',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginLeft: 8,
  },
  templateBadgeGlobal: { backgroundColor: '#f59e0b' },
  templateActions: { flexDirection: 'row', gap: 8 },
  editBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: '#dbeafe',
  },
  editBtnText: { fontSize: 12, color: '#2563eb', fontWeight: '500' },
  deleteBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: '#fee2e2',
  },
  deleteBtnText: { fontSize: 12, color: '#dc2626', fontWeight: '500' },

  // Duration config card
  durationCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  durationCardHeaderIcon: { fontSize: 18 },
  durationCardHeaderTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1e293b',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  durationSeparator: {
    height: 1,
    backgroundColor: '#e2e8f0',
  },
  durationFieldWrap: { gap: 8 },
  durationFieldLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748b',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  durationDropdownTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    padding: 12,
    backgroundColor: '#fff',
  },
  durationDropdownIcon: { fontSize: 16, color: '#94a3b8' },
  durationDropdownValue: { flex: 1, fontSize: 14, color: '#1e293b' },
  durationDropdownPlaceholder: { flex: 1, fontSize: 14, color: '#94a3b8' },
  durationDropdownChevron: { fontSize: 10, color: '#94a3b8' },
  durationDropdownList: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    backgroundColor: '#fff',
    maxHeight: 200,
    overflow: 'hidden',
  },
  durationDropdownItem: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  durationDropdownItemSelected: { backgroundColor: '#dbeafe' },
  durationDropdownItemText: { fontSize: 14, color: '#334155' },
  durationDropdownItemTextSelected: { color: '#1d4ed8', fontWeight: '700' },
  durationFieldHint: { fontSize: 12, color: '#94a3b8' },

  // Empty
  emptyDay: { fontSize: 13, color: '#94a3b8', fontStyle: 'italic', padding: 12 },

  // New day card
  dayCardOuter: {
    backgroundColor: '#fff',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  dayCardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  dayCardBody: {
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 10,
  },
  dayCollapseBtn: { padding: 4 },
  dayCollapseBtnText: { fontSize: 14, color: '#94a3b8', width: 18, textAlign: 'center' },
  dayNumberBadge: {
    width: 40,
    height: 40,
    backgroundColor: '#f8fafc',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayNumberBadgeText: { fontSize: 15, fontWeight: '700', color: '#64748b' },
  dayTitleBlock: { gap: 1 },
  dayTitleMain: { fontSize: 14, fontWeight: '700', color: '#1e293b' },
  dayTitleSub: { fontSize: 11, color: '#94a3b8' },
  daySessionInput: {
    flex: 1,
    fontSize: 13,
    color: '#1e293b',
    paddingHorizontal: 8,
    paddingVertical: 4,
    minWidth: 100,
  },
  dayHeaderRight: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  dayAddExerciseBtn: {
    borderWidth: 1,
    borderColor: '#3b82f6',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  dayAddExerciseBtnText: { color: '#3b82f6', fontSize: 12, fontWeight: '600' },
  dayMoveBtn: { padding: 4 },
  dayMoveBtnText: { fontSize: 13, color: '#94a3b8' },
  dayTrashBtn: { padding: 4 },
  dayTrashBtnText: { fontSize: 16, color: '#94a3b8' },

  // New block body
  blockBodyRow: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 12,
    paddingBottom: 12,
    paddingTop: 4,
  },
  blockImageCol: {
    flexDirection: 'column',
    alignItems: 'center',
    gap: 4,
    flexShrink: 0,
  },
  blockImageWrap: {
    width: 96,
    height: 96,
    borderRadius: 8,
    overflow: 'hidden',
    flexShrink: 0,
  },
  blockBodyImage: { width: '100%', height: '100%' },
  blockBodyFieldsWrap: { flex: 1, flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  blockActionSep: { width: 1, height: 16, backgroundColor: '#e2e8f0', marginHorizontal: 2 },
  blockEditBtn: { padding: 6, borderRadius: 6, backgroundColor: '#f1f5f9' },
  blockEditBtnActive: { backgroundColor: '#dbeafe' },
  blockEditBtnText: { fontSize: 13 },
  blockTrashBtn: { padding: 6, borderRadius: 6, backgroundColor: '#fee2e2' },
  blockTrashBtnText: { fontSize: 13, color: '#dc2626' },
  blockCollapseBtn: { padding: 6 },
  blockCollapseBtnText: { fontSize: 13, color: '#94a3b8' },

  // Plan 72
  readOnlyBadge: {
    backgroundColor: '#f8fafc',
    borderColor: '#e2e8f0',
    borderWidth: 1,
    padding: 8,
    borderRadius: 8,
    marginBottom: 8,
  },
  readOnlyText: { color: '#64748b', fontSize: 12, fontStyle: 'italic', textAlign: 'center' },
});
