import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  body: { flex: 1, flexDirection: 'row' },
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    width: 'calc(25% - 18px)' as unknown as number,
  },
  cardContent: { padding: 12 },
  cardGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 24,
  },
  cardImage: { height: 160, width: '100%', overflow: 'hidden' },
  cardImageInner: {
    height: '100%',
    width: '100%',
    transitionProperty: 'transform',
    transitionDuration: '0.3s',
    transitionTimingFunction: 'ease-in-out',
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
  } as any, // Cast to any to bypass strict RN style types for web-only transition properties
  cardImageInnerHovered: {
    transform: [{ scale: 1.15 }],
  },
  cardImagePlaceholder: {
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
    height: '100%',
    justifyContent: 'center',
    width: '100%',
  },
  cardTag: {
    backgroundColor: 'rgba(37, 99, 235, 0.08)',
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  cardTagText: { color: '#2563eb', fontSize: 10, fontWeight: '700', letterSpacing: 0.5 },
  cardTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 6 },
  cardTitle: { color: '#0f172a', fontSize: 14, fontWeight: '600' },
  categoryIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(37, 99, 235, 0.08)',
    borderRadius: 8,
    height: 28,
    justifyContent: 'center',
    marginRight: 10,
    width: 28,
  },
  categoryLabel: { color: '#334155', flex: 1, fontSize: 13, fontWeight: '500' },
  categoryLabelActive: { color: '#2563eb', fontWeight: '600' },
  categoryRow: {
    alignItems: 'center',
    borderRadius: 8,
    flexDirection: 'row',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  categoryRowActive: {
    backgroundColor: 'rgba(37, 99, 235, 0.06)',
  },
  chip: {
    backgroundColor: '#f1f5f9',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  chipContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  chipSelected: { backgroundColor: '#2563eb' },
  chipText: { color: '#475569', fontSize: 12, fontWeight: '500' },
  chipTextSelected: { color: '#fff' },
  clearFilters: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    marginTop: 16,
    paddingHorizontal: 10,
  },
  clearFiltersText: { color: '#64748b', fontSize: 12 },
  divider: {
    backgroundColor: '#e2e8f0',
    height: 1,
    marginBottom: 8,
    marginTop: 4,
  },
  equipmentSubLabel: {
    color: '#94a3b8',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.8,
    paddingHorizontal: 10,
  },
  equipmentSubSection: {
    borderTopColor: '#f1f5f9',
    borderTopWidth: 1,
    marginTop: 4,
    paddingTop: 4,
  },
  chipSmall: {
    backgroundColor: '#f8fafc',
    borderColor: '#e2e8f0',
    borderRadius: 5,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  chipTextSmall: { color: '#64748b', fontSize: 11, fontWeight: '500' },
  emptyState: {
    alignItems: 'center',
    gap: 8,
    justifyContent: 'center',
    paddingVertical: 80,
  },
  emptySubtext: { color: '#94a3b8', fontSize: 13 },
  emptyText: { color: '#64748b', fontSize: 16, fontWeight: '600' },
  filtersSection: {
    marginTop: 8,
  },
  header: {
    alignItems: 'center',
    borderBottomColor: '#e2e8f0',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 32,
    paddingVertical: 20,
  },
  headerLeft: { flex: 1 },
  headerRight: { alignItems: 'center', flexDirection: 'row', gap: 12 },
  headerSubtitle: { color: '#64748b', fontSize: 13, marginTop: 2 },
  headerTitle: { color: '#0f172a', fontSize: 22, fontWeight: '700' },
  imageBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  imageShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(7, 12, 20, 0.2)',
  },
  loadingText: { color: '#94a3b8', fontSize: 14, paddingVertical: 40 },
  mainContent: { flex: 1 },
  mainContentInner: { padding: 24 },
  newButton: {
    alignItems: 'center',
    backgroundColor: '#2563eb',
    borderRadius: 10,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  newButtonText: { color: '#fff', fontSize: 13, fontWeight: '600' },
  root: { backgroundColor: '#f8fafc', flex: 1 },
  searchContainer: {
    alignItems: 'center',
    backgroundColor: '#fff',
    borderColor: '#e2e8f0',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    width: 240,
  },
  searchInput: { color: '#0f172a', flex: 1, fontSize: 13, outlineStyle: 'none' as unknown as undefined },
  sidebar: {
    backgroundColor: '#fff',
    borderRightColor: '#e2e8f0',
    borderRightWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 16,
    width: 230,
  },
  sidebarTitle: {
    color: '#94a3b8',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1,
    marginBottom: 12,
    paddingHorizontal: 10,
  },
  tagPrimary: {
    backgroundColor: '#dbeafe',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  tagPrimaryText: {
    color: '#2563eb',
    fontSize: 10,
    fontWeight: '700',
  },
  tagSecondary: {
    backgroundColor: '#f1f5f9',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  tagSecondaryText: {
    color: '#64748b',
    fontSize: 10,
    fontWeight: '700',
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'flex-end',
    marginTop: 8,
  },
  actionBtn: {
    backgroundColor: '#f1f5f9',
    borderRadius: 6,
    padding: 6,
  },
  actionDelete: {
    backgroundColor: '#fee2e2',
  },
  actionIcon: {
    fontSize: 12,
  },
  topChip: {
    backgroundColor: '#fff',
    borderColor: '#e2e8f0',
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  topChipBar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 20,
  },
  topChipSelected: { backgroundColor: '#2563eb', borderColor: '#2563eb' },
  topChipText: { color: '#475569', fontSize: 12, fontWeight: '500' },
  topChipTextSelected: { color: '#fff' },
});
