import { StyleSheet } from 'react-native';

export const theme = {
  colors: {
    background: '#ffffff',
    surface: '#f6f9ff',
    primary: '#1c74e9',
    text: '#111418',
    textSecondary: '#5e7088',
    border: '#d4e0ef',
    danger: '#d92d20',
  },
  borderRadius: {
    md: 10,
    lg: 16,
  },
};

export const detailModalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(5, 10, 20, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
    // @ts-expect-error RN Web backdrop filter
    backdropFilter: 'blur(8px)',
    WebkitBackdropFilter: 'blur(8px)',
  },
  container: {
    width: '100%',
    maxWidth: 1000,
    maxHeight: '90%',
    backgroundColor: '#fff',
    borderRadius: 30,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
  },
  header: {
    paddingTop: 20,
    paddingHorizontal: 30,
  },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  backText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#5e7088',
  },
  scroll: { flex: 1 },
  scrollContent: { padding: 40, paddingTop: 20 },
  heroWrapper: { flexDirection: 'row', gap: 40, marginBottom: 40 },
  heroLeft: { width: 350 },
  heroRight: { flex: 1 },
  mediaBox: {
    width: '100%',
    aspectRatio: 1.2,
    borderRadius: 24,
    backgroundColor: '#000',
    overflow: 'hidden',
    position: 'relative',
  },
  mediaBlur: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    opacity: 0.6,
  },
  mediaMain: { width: '100%', height: '100%' },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: 30,
  },
  title: { fontSize: 42, fontWeight: '800', color: '#0f172a' },
  alias: { fontSize: 36, fontWeight: '600', color: '#cbd5e1' },
  infoGrid: { flexDirection: 'row', gap: 30 },
  infoCol: { flex: 1 },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#1c74e9',
  },
  dotSelection: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#3b82f6',
  },
  sectionTitleCap: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
    color: '#94a3b8',
  },
  tagContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  tag: {
    backgroundColor: '#f1f5f9',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  tagText: { fontSize: 12, fontWeight: '600', color: '#475569' },
  equipmentCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 12,
    backgroundColor: '#fff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#f1f5f9',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  equipmentIconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#eff6ff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  equipmentName: { fontSize: 14, fontWeight: '700', color: '#1e293b' },
  equipmentSub: {
    fontSize: 8,
    fontWeight: '600',
    color: '#94a3b8',
    marginTop: 2,
  },
  contentRow: { flexDirection: 'row', gap: 24, marginBottom: 40 },
  contentCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  fullWidth: { flex: 1 },
  contentCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 20,
  },
  contentCardTitleWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  contentCardTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1e293b',
    letterSpacing: 0.3,
  },
  descriptionText: {
    fontSize: 14,
    lineHeight: 22,
    color: '#64748b',
    fontWeight: '500',
  },
  videoPreview: {
    width: '100%',
    aspectRatio: 1.6,
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    overflow: 'hidden',
  },
  footer: {
    flexDirection: 'row',
    gap: 30,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    paddingTop: 24,
  },
  footerItem: {},
  footerLabel: { fontSize: 8, fontWeight: '700', color: '#94a3b8', marginBottom: 4 },
  footerValue: { fontSize: 13, fontWeight: '700', color: '#1e293b' },
  emptyText: { fontSize: 12, color: '#94a3b8', fontStyle: 'italic' },
});
