import { StyleSheet } from 'react-native';

export const theme = {
  colors: {
    background: '#f6f9fc',
    surface: '#ffffff',
    primary: '#475569',
    primaryAlpha: 'rgba(71, 85, 105, 0.7)',
    text: '#0f172a',
    textSecondary: '#64748b',
    border: '#e2e8f0',
    danger: '#ef4444',
  },
  borderRadius: {
    md: 12,
    lg: 20,
    xl: 32,
  },
};

export const detailModalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(5, 10, 20, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
    // @ts-expect-error RN Web backdrop filter
    backdropFilter: 'blur(8px)',
    WebkitBackdropFilter: 'blur(8px)',
  },
  container: {
    width: '100%',
    maxWidth: 1000,
    maxHeight: '90%',
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.xl,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
    display: 'flex',
  },
  header: {
    paddingTop: 24,
    paddingHorizontal: 40,
    paddingBottom: 4,
    backgroundColor: theme.colors.surface,
    zIndex: 10,
  },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  backText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#64748b',
  },
  scroll: { flex: 1, backgroundColor: theme.colors.background },
  scrollContent: { padding: 40 },
  heroWrapper: {
    flexDirection: 'row',
    gap: 40,
    marginBottom: 32,
  },
  heroLeft: {
    width: 320,
  },
  heroRight: {
    flex: 1,
  },
  mediaBox: {
    width: '100%',
    aspectRatio: 1.3,
    borderRadius: theme.borderRadius.lg,
    backgroundColor: '#000',
    overflow: 'hidden',
    position: 'relative',
  },
  mediaBlur: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    opacity: 0.6,
  },
  mediaMain: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  playOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.2)',
    justifyContent: 'flex-end',
    alignItems: 'flex-start',
    padding: 16,
  },
  playBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(255,255,255,0.2)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.4)',
    backdropFilter: 'blur(10px)',
  },
  playBtnText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: 32,
    flexWrap: 'wrap',
  },
  title: { fontSize: 44, fontWeight: '800', color: '#0f172a', marginRight: 12 },
  alias: { fontSize: 36, fontWeight: '600', color: '#cbd5e1' },
  infoGrid: { flexDirection: 'row', gap: 32 },
  infoCol: { flex: 1 },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 12,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#3b82f6',
  },
  sectionTitleCap: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
    color: '#94a3b8',
    textTransform: 'uppercase',
  },
  tagContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  tag: {
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  tagText: { fontSize: 13, fontWeight: '700', color: '#475569' },
  equipmentCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  equipmentIconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#eff6ff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  equipmentName: { fontSize: 14, fontWeight: '800', color: '#1e293b' },
  equipmentSub: {
    fontSize: 9,
    fontWeight: '800',
    color: '#94a3b8',
    marginTop: 2,
    textTransform: 'uppercase',
  },
  descContainer: {
    flexDirection: 'row',
    gap: 32,
    marginBottom: 32,
    alignItems: 'stretch',
  },
  descCard: {
    flex: 1,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.lg,
    padding: 32,
    borderColor: theme.colors.border,
    borderWidth: 1,
    minHeight: 280,
  },
  descHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 20,
  },
  descTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1e293b',
    textTransform: 'uppercase',
    letterSpacing: 0.2,
  },
  descriptionText: {
    fontSize: 15,
    lineHeight: 24,
    color: '#475569',
    fontWeight: '500',
  },
  footer: {
    flexDirection: 'row',
    gap: 48,
    paddingHorizontal: 8,
  },
  footerItem: {},
  footerLabel: { fontSize: 9, fontWeight: '800', color: '#94a3b8', marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.5 },
  footerValue: { fontSize: 14, fontWeight: '800', color: '#0f172a' },
  emptyText: { fontSize: 13, color: '#94a3b8', fontStyle: 'italic', fontWeight: '500' },
});
