export const SERIES_COL_W = 48;

export const st = {
  row: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  headerRow: {
    backgroundColor: '#f8fafc',
    borderRadius: 6,
    borderBottomWidth: 0,
    paddingVertical: 6,
  },
  rowEven: { backgroundColor: '#fff' },
  rowOdd: { backgroundColor: '#fafafa' },
  headerCell: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 4,
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  headerText: {
    fontSize: 11,
    fontWeight: '600' as const,
    color: '#64748b',
  },
  headerTextLocked: { color: '#cbd5e1' },
  lockBtn: { padding: 2 },
  lockIcon: { fontSize: 11, color: '#94a3b8' },
  lockIconActive: { color: '#ef4444' },
  actionCell: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 4,
    paddingVertical: 6,
  },
  actionBtn: { padding: 4 },
  actionIcon: { fontSize: 14, color: '#cbd5e1' },
  actionIconActive: { color: '#3b82f6' },
  actionIconRemove: { fontSize: 12, color: '#f87171' },
  seriesCell: {
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingVertical: 6,
    gap: 2,
  },
  seriesCellClickable: { cursor: 'pointer' } as { cursor: 'pointer' },
  seriesNumber: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: '#475569',
  },
  seriesNumberBtn: {
    minWidth: 28,
    minHeight: 28,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  seriesNumberBtnActive: {
    backgroundColor: '#fef9c3',
    borderColor: '#fbbf24',
  },
  seriesNumberBtnText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: '#ef4444',
  },
  seriesNumberBtnTextActive: {
    color: '#92400e',
  },
  advancedLabelRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 2,
    width: SERIES_COL_W - 4,
    overflow: 'hidden' as const,
  },
  advancedLabel: {
    fontSize: 9,
    fontWeight: '700' as const,
    color: '#374151',
    flexShrink: 1,
  },
  advancedRemoveIcon: {
    fontSize: 9,
    color: '#ef4444',
    fontWeight: '700' as const,
    lineHeight: 12,
  },
  copyBtn: { marginTop: 2 },
  copyIcon: { fontSize: 12, color: '#3b82f6' },
  dataCell: {
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  dataCellLocked: { backgroundColor: '#f8fafc' },
  cellInput: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 6,
    fontSize: 12,
    color: '#1e293b',
    textAlign: 'center' as const,
    backgroundColor: '#fff',
  },
  cellInputReadOnly: { backgroundColor: '#f8fafc', color: '#64748b' },
};
