import { StyleSheet } from 'react-native';

export const s = StyleSheet.create({
  body: {
    gap: 16,
    marginTop: 12,
    flex: 1,
  },
  bodyColumn: {
    flexDirection: 'column',
  },
  bodyRow: {
    flexDirection: 'row',
  },
  cancelBtn: {
    alignItems: 'center',
    backgroundColor: '#64748b',
    borderRadius: 8,
    marginTop: 12,
    paddingVertical: 12,
  },
  cancelText: { color: '#fff', fontSize: 15, fontWeight: '600' },
  typeBar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  typeBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
  },
  typeBtnActive: {
    backgroundColor: '#dbeafe',
    borderColor: '#93c5fd',
  },
  typeBtnText: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: '600',
  },
  typeBtnTextActive: {
    color: '#1d4ed8',
  },
  footer: {
    alignItems: 'center',
    borderTopColor: '#e2e8f0',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
    paddingTop: 12,
  },
  footerCount: {
    color: '#64748b',
    flex: 1,
    fontSize: 13,
  },
  doneBtn: {
    alignItems: 'center',
    backgroundColor: '#1c74e9',
    borderRadius: 8,
    minWidth: 120,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  doneBtnText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  cardAddedBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#dcfce7',
    borderRadius: 4,
    marginTop: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  cardAddedBadgeText: {
    color: '#15803d',
    fontSize: 10,
    fontWeight: '700',
  },
  cardPrimaryBtnAdded: {
    backgroundColor: '#e2e8f0',
  },
  cardPrimaryTextAdded: {
    color: '#64748b',
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    overflow: 'hidden',
    flex: 1,
  },
  cardActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  cardBody: {
    padding: 12,
  },
  cardGhostBtn: {
    borderColor: '#cbd5f5',
    borderWidth: 1,
    borderRadius: 8,
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
  },
  cardGhostText: { color: '#1c74e9', fontSize: 12, fontWeight: '600' },
  cardGrid: {
    gap: 12,
    paddingBottom: 12,
  },
  cardImage: {
    height: 120,
    width: '100%',
  },
  cardImageFrame: {
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
    justifyContent: 'center',
    padding: 6,
  },
  cardPrimaryBtn: {
    backgroundColor: '#1c74e9',
    borderRadius: 8,
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
  },
  cardPrimaryText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  cardRow: {
    gap: 12,
  },
  cardSubtitle: { color: '#64748b', fontSize: 12, lineHeight: 16, marginTop: 4 },
  cardTitle: { color: '#0f172a', fontSize: 14, fontWeight: '700' },
  detailColumn: {
    flex: 1,
    minWidth: 260,
  },
  detailEmpty: {
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    justifyContent: 'center',
    minHeight: 200,
    padding: 16,
  },
  detailEmptyText: {
    color: '#64748b',
    fontSize: 13,
    textAlign: 'center',
  },
  detailLabel: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  detailName: {
    color: '#0f172a',
    fontSize: 16,
    fontWeight: '700',
  },
  detailPanel: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    overflow: 'hidden',
  },
  detailMediaWrapper: {
    height: 240,
    width: '100%',
    backgroundColor: '#0f172a',
  },
  detailContent: {
    padding: 24,
    gap: 16,
  },
  detailSection: {
    gap: 6,
  },
  detailTitle: {
    color: '#1e293b',
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  detailValue: {
    color: '#1e293b',
    fontSize: 13,
    lineHeight: 18,
  },
  empty: { color: '#64748b', marginTop: 24, textAlign: 'center' },
  list: { flex: 1, overflow: 'hidden' },
  listColumn: {
    flex: 2,
    minWidth: 280,
    flexBasis: 0,
  },
  loader: { marginTop: 24 },
  overlay: {
    backgroundColor: 'rgba(0,0,0,0.45)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  search: {
    backgroundColor: '#f1f5f9',
    borderRadius: 8,
    fontSize: 14,
    marginBottom: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  sheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    height: '85%',
    maxHeight: '85%',
    paddingBottom: 32,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  title: {
    color: '#0f172a',
    fontSize: 17,
    fontWeight: '700',
    marginBottom: 12,
  },
});
