import { NOTE_ACTION_COL_W } from './warmup-exercise-list.constants';

export const md = {
  overlay: {
    flex: 1,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    padding: 20,
  },
  backdrop: {
    ...({
      position: 'absolute' as const,
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(15, 23, 42, 0.45)',
    } as const),
  },
  sheet: {
    backgroundColor: '#fff',
    borderRadius: 14,
    maxHeight: '85vh' as unknown as number,
    maxWidth: 560,
    width: '100%' as const,
    alignSelf: 'center' as const,
    overflow: 'hidden' as const,
    zIndex: 1,
  },
  header: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  title: { flex: 1, fontSize: 16, fontWeight: '700' as const, color: '#0f172a', paddingRight: 8 },
  closeBtn: { padding: 8, backgroundColor: '#f1f5f9', borderRadius: 8 },
  closeText: { fontSize: 14, color: '#475569' },
  body: { maxHeight: '72vh' as unknown as number },
  bodyContent: { padding: 16, gap: 16, paddingBottom: 24 },
  muted: { fontSize: 13, color: '#64748b', lineHeight: 18 },
  bodyText: { fontSize: 14, color: '#334155', lineHeight: 20 },
};

export const el = {
  container: { paddingBottom: 8 },
  empty: { padding: 16 },
  emptyText: { fontSize: 12, color: '#94a3b8', fontStyle: 'italic' as const },

  row: {
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    paddingTop: 10,
    paddingBottom: 6,
    paddingHorizontal: 14,
  },
  rowHeader: {
    flexDirection: 'row' as const,
    alignItems: 'flex-start' as const,
    gap: 8,
    marginBottom: 8,
  },
  rowName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700' as const,
    color: '#0f172a',
    lineHeight: 18,
  },
  rowActions: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 4,
    flexShrink: 0,
  },
  typeBadge: {
    borderRadius: 5,
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  typeBadgeText: { fontSize: 10, fontWeight: '700' as const },
  actionBtn: { paddingHorizontal: 5, paddingVertical: 2 },
  actionBtnText: { fontSize: 14, color: '#64748b' },

  body: { gap: 10 },
  bodyTopRow: {
    flexDirection: 'row' as const,
    gap: 12,
    alignItems: 'flex-start' as const,
  },
  mobilityImageCol: {
    flexShrink: 0,
    width: 80,
    gap: 6,
  },
  linkUnderImage: { paddingTop: 4, alignItems: 'center' as const },
  linkUnderImageText: {
    fontSize: 11,
    fontWeight: '500' as const,
    color: '#3b82f6',
    lineHeight: 14,
  },
  image: {
    width: 80,
    height: 80,
    borderRadius: 6,
    backgroundColor: '#e2e8f0',
    flexShrink: 0,
  },
  globalChips: {
    flex: 1,
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    gap: 16,
    alignItems: 'flex-start' as const,
  },
  chipField: { gap: 2 },
  chipLabel: {
    fontSize: 10,
    color: '#94a3b8',
    fontWeight: '500' as const,
  },
  chipValue: {
    fontSize: 20,
    fontWeight: '700' as const,
    color: '#1e293b',
    lineHeight: 24,
  },

  setsSection: { gap: 6 },
  setsTitle: {
    fontSize: 11,
    fontWeight: '700' as const,
    color: '#64748b',
    letterSpacing: 0.8,
  },
  tableHeaderRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    paddingBottom: 4,
    marginBottom: 2,
  },
  tableNoteHeaderCell: {
    width: NOTE_ACTION_COL_W,
    flexShrink: 0,
  },
  tableNoteActionCell: {
    width: NOTE_ACTION_COL_W,
    flexShrink: 0,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    paddingVertical: 2,
  },
  setNoteBtn: {
    padding: 6,
    borderRadius: 6,
  },
  setNoteIcon: {
    fontSize: 16,
    opacity: 0.45,
  },
  setNoteIconActive: {
    opacity: 1,
  },
  tableRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  tableCell: {
    width: 90,
    textAlign: 'center' as const,
    paddingHorizontal: 4,
  },
  tableCellSerie: { width: 52 },
  tableCellWide: { width: 160, textAlign: 'left' as const },
  tableHeaderWide: { width: 160, textAlign: 'left' as const },
  tableHeaderText: {
    fontSize: 11,
    fontWeight: '600' as const,
    color: '#94a3b8',
  },
  tableCellValue: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: '#1e293b',
  },

  circuitBox: {
    borderWidth: 1,
    borderColor: '#93c5fd',
    borderRadius: 8,
    backgroundColor: '#eff6ff',
    marginVertical: 4,
    paddingTop: 6,
    paddingBottom: 4,
    paddingHorizontal: 8,
  },
  circuitHeaderRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
    marginBottom: 2,
  },
  circuitLabel: {
    fontSize: 9,
    fontWeight: '700' as const,
    color: '#1d4ed8',
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
  },
  circuitNote: {
    fontSize: 11,
    color: '#3b82f6',
    fontStyle: 'italic' as const,
  },
};
