import { StyleSheet } from 'react-native';

export const COLORS = {
  accent: '#1c74e9',
  border: '#dfe8f5',
  card: '#ffffff',
  page: '#f6f7f8',
  success: '#0a7c42',
  successBg: '#ecfdf5',
  text: '#111418',
  textMuted: '#6a7381',
  warning: '#d92d20',
};

export const styles = StyleSheet.create({
  accentButton: {
    alignItems: 'center',
    backgroundColor: COLORS.accent,
    borderRadius: 10,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 16,
  },
  accentButtonLabel: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: '#eaf2ff',
    borderRadius: 999,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  avatarLabel: {
    color: '#225fdb',
    fontSize: 12,
    fontWeight: '800',
  },
  avatarLabelMuted: {
    color: COLORS.textMuted,
  },
  avatarMuted: {
    backgroundColor: '#f0f0f0',
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  container: {
    gap: 14,
    maxWidth: 980,
    width: '100%',
  },
  copyButton: {
    alignItems: 'center',
    borderColor: COLORS.success,
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  copyButtonLabel: {
    color: COLORS.success,
    fontSize: 12,
    fontWeight: '700',
  },
  createButton: {
    alignItems: 'center',
    backgroundColor: COLORS.accent,
    borderRadius: 10,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 14,
  },
  createButtonLabel: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  dangerButton: {
    alignItems: 'center',
    borderColor: COLORS.warning,
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 12,
  },
  dangerLabel: {
    color: COLORS.warning,
    fontSize: 12,
    fontWeight: '700',
  },
  empty: {
    color: COLORS.textMuted,
    fontSize: 14,
    paddingVertical: 8,
  },
  ghostButton: {
    alignItems: 'center',
    borderColor: COLORS.border,
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 12,
  },
  ghostLabel: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  hero: {
    backgroundColor: COLORS.card,
    borderColor: COLORS.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 8,
    padding: 16,
  },
  heroTop: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  heroTitles: {
    flex: 1,
    gap: 2,
    paddingRight: 12,
  },
  list: {
    gap: 10,
  },
  modalActions: {
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'flex-end',
    marginTop: 4,
  },
  modalCard: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    gap: 14,
    maxWidth: 420,
    padding: 20,
    width: '90%',
  },
  modalInput: {
    borderColor: COLORS.border,
    borderRadius: 10,
    borderWidth: 1,
    color: COLORS.text,
    fontSize: 14,
    minHeight: 40,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  modalOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.4)',
    flex: 1,
    justifyContent: 'center',
  },
  modalTitle: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: '800',
  },
  page: {
    alignItems: 'center',
    backgroundColor: COLORS.page,
    flexGrow: 1,
    padding: 22,
  },
  pill: {
    backgroundColor: '#f2f6fd',
    borderColor: COLORS.border,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  pillLabel: {
    color: COLORS.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  pillsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  pillValue: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '800',
  },
  resultBanner: {
    alignItems: 'center',
    backgroundColor: COLORS.successBg,
    borderColor: COLORS.success,
    borderRadius: 12,
    borderWidth: 1,
    bottom: 24,
    flexDirection: 'row',
    left: 24,
    padding: 12,
    position: 'absolute',
    right: 24,
  },
  resultClose: {
    marginLeft: 8,
    padding: 4,
  },
  resultCloseLabel: {
    color: COLORS.textMuted,
    fontSize: 14,
    fontWeight: '700',
  },
  resultContent: {
    flex: 1,
    gap: 4,
  },
  resultPassword: {
    color: COLORS.text,
    fontFamily: 'monospace',
    fontSize: 14,
    fontWeight: '700',
  },
  resultText: {
    color: COLORS.success,
    fontSize: 13,
    fontWeight: '600',
  },
  row: {
    alignItems: 'center',
    backgroundColor: COLORS.card,
    borderColor: COLORS.border,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 14,
  },
  rowActions: {
    flexDirection: 'row',
    gap: 8,
  },
  rowArchived: {
    opacity: 0.75,
  },
  rowIdentity: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  rowStatus: {
    color: COLORS.textMuted,
    fontSize: 12,
    marginTop: 2,
  },
  rowTitle: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: '700',
  },
  rowTitleMuted: {
    color: COLORS.textMuted,
  },
  subtitle: {
    color: COLORS.textMuted,
    fontSize: 13,
  },
  successButton: {
    alignItems: 'center',
    borderColor: COLORS.success,
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 12,
  },
  successLabel: {
    color: COLORS.success,
    fontSize: 12,
    fontWeight: '700',
  },
  tabBar: {
    backgroundColor: COLORS.card,
    borderColor: COLORS.border,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    padding: 4,
  },
  tabButton: {
    alignItems: 'center',
    borderRadius: 9,
    flex: 1,
    justifyContent: 'center',
    paddingVertical: 8,
  },
  tabButtonActive: {
    backgroundColor: COLORS.accent,
  },
  tabButtonLabel: {
    color: COLORS.textMuted,
    fontSize: 13,
    fontWeight: '700',
  },
  tabButtonLabelActive: {
    color: '#ffffff',
  },
  title: {
    color: COLORS.text,
    fontSize: 24,
    fontWeight: '800',
  },
});
