export type CardioMethodSeed = {
  id: string;
  methodTypeCode: string;
  name: string;
  equipmentCode: string;
  description: string | null;
  coachInstructions: string | null;
  youtubeUrl: string;
};

export const CARDIO_METHODS_V1: CardioMethodSeed[] = [
  {
    id: "a176d025-62fa-4510-a119-0dcc32f3e391",
    name: "Seal Jacks",
    methodTypeCode: "activacion",
    equipmentCode: "undefined",
    description: "Salto abriendo y cerrando piernas simultáneamente mientras los brazos se abren y cierran de forma horizontal frente al pecho. El movimiento busca la apertura torácica y la coordinación rítmica, elevando la frecuencia cardíaca de forma progresiva.",
    coachInstructions: "• Mantén los brazos a la altura de los hombros sin que caigan durante el ejercicio.\n\n• Aterriza siempre con la parte delantera del pie para amortiguar el impacto.\n\n• Coordina la apertura de brazos con la apertura de piernas de forma rítmica.\n\n• Junta las escápulas activamente al abrir los brazos para calentar la espalda alta.\n\n• Mantén el core firme para evitar balanceos excesivos del torso.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "79387d42-3444-4b8f-80da-b8ca4715525c",
    name: "Cross Jacks",
    methodTypeCode: "activacion",
    equipmentCode: "undefined",
    description: "Salto coordinado donde, al cerrar, se cruza un brazo sobre otro y una pierna por delante de la otra de forma alterna. Es un ejercicio de agilidad mental y física que activa la musculatura interna de los muslos y los hombros.",
    coachInstructions: "• Alterna el brazo y la pierna que quedan por delante en cada repetición.\n\n• Mantén un ritmo fluido, evitando pausas entre los saltos de apertura y cruce.\n\n• Los brazos deben permanecer estirados y firmes durante todo el movimiento.\n\n• Enfócate en la velocidad de pies para mejorar la reactividad de los tobillos.\n\n• Mantén la mirada al frente para asegurar una postura erguida.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "3d953273-2f73-4198-8a0e-63a209a4de9b",
    name: "Heisman Jumps",
    methodTypeCode: "activacion",
    equipmentCode: "undefined",
    description: "Saltos laterales cortos (generalmente tres pasos) terminando con una pausa rítmica donde se eleva la rodilla interna hacia el pecho. Imita el movimiento de los jugadores de fútbol americano para mejorar el equilibrio dinámico y la potencia lateral.",
    coachInstructions: "• Mantén el centro de gravedad bajo durante los pasos laterales rápidos.\n\n• Al elevar la rodilla, el muslo debe quedar paralelo al suelo de forma explosiva.\n\n• Asegura el equilibrio en la pierna de apoyo durante la pausa del \"stick\".\n\n• Coordina el brazo opuesto con la rodilla elevada para mayor realismo y estabilidad.\n\n• Realiza el desplazamiento con pasos cortos y reactivos, sin \"arrastrar\" los pies.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "a50b63b1-2fd1-4a12-8b3e-40b91dbb5ae2",
    name: "Cross-Body Mountain Climbers",
    methodTypeCode: "activacion",
    equipmentCode: "undefined",
    description: "Desde posición de plancha frontal, se lleva la rodilla de forma alterna hacia el codo opuesto buscando una torsión controlada de la cintura. Combina la estabilidad de hombros con la activación de oblicuos y flexores de cadera.",
    coachInstructions: "• Mantén los hombros alineados verticalmente sobre las muñecas en todo momento.\n\n• Lleva la rodilla lo más cerca posible del codo opuesto sin elevar la cadera.\n\n• No permitas que la zona lumbar se hunda o se arquee durante la rotación.\n\n• Exhala con fuerza en cada cruce de rodilla para maximizar la contracción abdominal.\n\n• Mantén el cuello neutro, mirando al suelo un paso por delante de tus manos.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "acdcd88a-986d-4d35-b1f0-4a278f05dd43",
    name: "Inchworms",
    methodTypeCode: "activacion",
    equipmentCode: "undefined",
    description: "Desde posición de pie, te inclinas para tocar el suelo y caminas con las manos hasta llegar a una plancha, para luego volver. Es un ejercicio excelente para el estiramiento dinámico de la cadena posterior y el calentamiento de hombros.",
    coachInstructions: "• Mantén las piernas lo más estiradas posible para estirar femorales y gemelos.\n\n• Camina con las manos de forma controlada, evitando balancear la cadera lateralmente.\n\n• Al llegar a la plancha, bloquea el cuerpo como una tabla un segundo.\n\n• Empuja con fuerza desde las palmas para iniciar el regreso hacia los pies.\n\n• No des tirones bruscos al incorporarte a la posición vertical de pie.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "5bc9fdee-3d8d-4e3b-8a6a-a7831916e2e8",
    name: "Boxer Shuffle",
    methodTypeCode: "activacion",
    equipmentCode: "undefined",
    description: "Pequeños saltos ágiles cambiando el peso de un pie al otro de forma rítmica. Imita el descanso activo de los boxeadores, manteniendo el cuerpo en movimiento sin un gasto energético excesivo, ideal para transiciones.",
    coachInstructions: "• Mantén las rodillas relajadas y los tobillos muy reactivos (rebotando).\n\n• Los hombros y brazos deben estar relajados, acompañando el balanceo natural.\n\n• No apoyes los talones con fuerza; el peso debe estar en el metatarso.\n\n• Cambia el peso de forma fluida para mejorar la agilidad lateral y frontal.\n\n• Mantén la respiración nasal rítmica para oxigenar el cuerpo progresivamente.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "39f2b17d-4a82-4484-9e85-fc9612c95bb8",
    name: "Gate Swings",
    methodTypeCode: "activacion",
    equipmentCode: "undefined",
    description: "Salto abriendo las piernas en una sentadilla sumo (puntas hacia fuera) y salto para cerrar las piernas al centro. Se suelen apoyar las manos en los muslos para guiar la profundidad. Activa glúteos, aductores y cuádriceps.",
    coachInstructions: "• Al bajar a la sentadilla, empuja las rodillas hacia afuera siguiendo la punta de los pies.\n\n• Mantén el pecho alto y no permitas que la espalda se encorve al tocar las piernas.\n\n• Realiza el salto de cierre con potencia para trabajar la reactividad de las piernas.\n\n• Inhala al abrir en sentadilla y exhala al cerrar de forma explosiva.\n\n• Asegura que los talones estén siempre bien apoyados en la fase de apertura.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "c1dcc09f-a444-4534-9add-c5ed214fe8c5",
    name: "Power Skips",
    methodTypeCode: "activacion",
    equipmentCode: "undefined",
    description: "Saltos de potencia hacia arriba exagerando la elevación de una rodilla y el brazo contrario. Es una versión explosiva de correr en el sitio que busca ganar altura y activar la potencia de tobillo y cadera.",
    coachInstructions: "• Impúlsate con fuerza desde la puntera del pie para buscar la máxima verticalidad.\n\n• Lleva la rodilla elevada con decisión hacia el pecho en cada salto.\n\n• Coordina el braceo de forma enérgica para ayudar al impulso ascendente del cuerpo.\n\n• Aterriza con suavidad sobre la parte delantera del pie para proteger las rodillas.\n\n• Mantén el core bloqueado para evitar que el torso se incline hacia atrás al saltar.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "3df21d65-be36-4264-9c2c-91ec705cc894",
    name: "Lateral Toe Taps",
    methodTypeCode: "activacion",
    equipmentCode: "undefined",
    description: "Toques rápidos y alternos de puntera en el sitio o sobre un objeto imaginario, buscando la máxima frecuencia de pies. Mejora la coordinación neuromuscular y eleva rápidamente las pulsaciones.",
    coachInstructions: "• Mantén el centro de gravedad ligeramente bajo y las rodillas desbloqueadas.\n\n• Toca el suelo de forma mínima y rápida; imagina que el suelo \"quema\".\n\n• El torso debe permanecer casi inmóvil mientras las piernas se mueven a máxima velocidad.\n\n• Coordina el movimiento con un braceo corto y rápido a los lados del cuerpo.\n\n• Enfócate en la reactividad de los tobillos para mejorar la agilidad.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "3d68deb5-770d-4931-97c6-a30520930b7e",
    name: "Plank Toads",
    methodTypeCode: "activacion",
    equipmentCode: "undefined",
    description: "Desde posición de plancha frontal, se realiza un salto con ambos pies hacia la parte externa de las manos y se vuelve a la plancha. Es un movimiento explosivo que requiere gran movilidad de cadera y control del core.",
    coachInstructions: "• Al saltar hacia las manos, intenta que los pies aterricen planos fuera de los brazos.\n\n• Mantén la espalda lo más recta posible al llegar a la posición de cuclillas.\n\n• Regresa a la plancha de forma controlada sin que la cadera se hunda hacia el suelo.\n\n• Mantén la mirada entre las manos para asegurar la alineación cervical.\n\n• Utiliza el abdomen para amortiguar el regreso y estabilizar los hombros.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "bed43a6f-21fa-45a2-b659-70d46ff2e0ad",
    name: "Patadas frontales de cardio",
    methodTypeCode: "activacion",
    equipmentCode: "undefined",
    description: "Patadas alternas hacia adelante a media altura manteniendo un ritmo constante. El objetivo es estirar dinámicamente la cadena posterior y elevar la temperatura corporal sin impacto excesivo.",
    coachInstructions: "• Lanza la patada de forma controlada; no des tirones bruscos con la rodilla.\n\n• Mantén el core firme para evitar que el cuerpo se incline hacia atrás al patear.\n\n• Intenta tocar la punta del pie con la mano contraria para añadir coordinación.\n\n• La pierna de apoyo debe permanecer ligeramente flexionada para mayor estabilidad.\n\n• Mantén un ritmo fluido, inhalando al bajar y exhalando al lanzar la patada.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "4da7dc8f-eb4e-4e2d-896d-e8e87667c2ae",
    name: "Patadas laterales de cardio",
    methodTypeCode: "activacion",
    equipmentCode: "undefined",
    description: "Patadas hacia los lados de forma alterna. Busca activar el glúteo medio y los aductores en el plano lateral, mejorando la movilidad de la articulación de la cadera en este rango.",
    coachInstructions: "• Mantén el torso estable y evita inclinarte excesivamente hacia el lado opuesto.\n\n• La punta del pie debe mirar hacia el frente durante la patada, no hacia el techo.\n\n• Controla el descenso de la pierna para no perder el equilibrio.\n\n• No es necesario buscar altura máxima; prioriza el control técnico sobre el rango.\n\n• Mantén la mirada al frente para asegurar una postura erguida.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "59720076-1eb1-4d1e-96a1-815956b32b3a",
    name: "Grapevine",
    methodTypeCode: "activacion",
    equipmentCode: "undefined",
    description: "Paso lateral coordinado donde un pie cruza por detrás del otro alternativamente. Es un patrón de movimiento rítmico clásico que mejora la agilidad lateral y la coordinación de piernas.",
    coachInstructions: "• Realiza el cruce de pies de forma fluida, sin tropezar ni mirar al suelo.\n\n• Mantén un ritmo constante y acompaña el movimiento con un braceo natural.\n\n• El centro de gravedad debe permanecer a la misma altura durante todo el recorrido.\n\n• Abre los brazos lateralmente para mejorar el equilibrio dinámico.\n\n• Enfócate en la rapidez del cruce de pies para aumentar la reactividad.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "05e18807-3be5-4de0-83a0-b9d8b31a585e",
    name: "Salto de comba imaginario",
    methodTypeCode: "activacion",
    equipmentCode: "undefined",
    description: "Simulación del movimiento de saltar a la cuerda realizando pequeños rebotes y moviendo las muñecas de forma circular. Permite trabajar la agilidad de tobillo sin la interrupción de la cuerda real.",
    coachInstructions: "• Mantén los saltos cortos y rápidos, despegando apenas unos centímetros del suelo.\n\n• Los codos deben estar pegados a los costados y el giro debe nacer de las muñecas.\n\n• Aterriza siempre sobre la parte delantera del pie para minimizar el impacto articular.\n\n• Coordina el salto con el giro imaginario de la muñeca para mayor realismo.\n\n• Mantén las rodillas ligeramente relajadas, evitando bloqueos bruscos.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "f4c811da-fb3d-4886-8c22-4f663894e85e",
    name: "Sprints laterales cortos",
    methodTypeCode: "activacion",
    equipmentCode: "undefined",
    description: "Desplazamientos laterales rápidos de pocos metros (2-3m), tocando el suelo con la mano al final de cada tramo antes de cambiar de dirección. Trabaja la agilidad, la frenada excéntrica y la potencia de arranque.",
    coachInstructions: "• Baja el centro de gravedad antes de tocar el suelo para estabilizar la frenada.\n\n• Mantén los pies paralelos y evita cruzarlos durante el desplazamiento lateral rápido.\n\n• Empuja con fuerza el suelo con la pierna exterior para iniciar el cambio de sentido.\n\n• Mantén la espalda recta y no encorves el torso al ir a tocar el suelo.\n\n• Realiza el ejercicio con máxima intensidad de pies (pasos cortos y rápidos).",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "4d12562d-d8c0-4e45-ad1b-8a2094fdc1af",
    name: "Windmill Skaters",
    methodTypeCode: "activacion",
    equipmentCode: "undefined",
    description: "Variante del patinador lateral (salto de lado a lado) exagerando la rotación del tronco para tocar el suelo con la mano opuesta a la pierna que apoya. Gran componente de potencia lateral y estabilidad de core.",
    coachInstructions: "• Realiza un salto lateral potente y asegura el equilibrio al aterrizar con una pierna.\n\n• El torso debe rotar desde la cintura para que la mano llegue al suelo con control.\n\n• Mantén la rodilla de la pierna de apoyo alineada con la punta del pie al bajar.\n\n• La pierna trasera puede quedar en el aire o rozar el suelo para mayor estabilidad.\n\n• Enfócate en la explosividad lateral al cambiar de una pierna a la otra.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "5702867d-5cc3-4ca8-ab87-a7cb628f74f9",
    name: "Burpees",
    methodTypeCode: "activacion",
    equipmentCode: "undefined",
    description: "Movimiento combinado que incluye una flexión de brazos (o pecho a tierra), salto a posición de cuclillas y salto vertical con palmada sobre la cabeza. Es el ejercicio de cardio por excelencia para calentar todo el cuerpo.",
    coachInstructions: "• Al bajar las manos al suelo, mantén la espalda recta y salta hacia atrás a la plancha.\n\n• No permitas que la cadera se hunda al realizar la flexión de brazos.\n\n• Salta con los pies hacia adelante buscando que aterricen planos y cerca de las manos.\n\n• El salto vertical debe ser explosivo, extendiendo cadera y rodillas por completo.\n\n• Coordina la respiración: exhala al saltar hacia arriba e inhala al bajar al suelo.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "b832e762-64dd-43af-bacc-11727630d854",
    name: "Rodillas arriba (High Knees)",
    methodTypeCode: "activacion",
    equipmentCode: "undefined",
    description: "Carrera estática exagerando la elevación de las rodillas hasta la altura de la cadera. El objetivo es elevar la temperatura muscular y trabajar la potencia de los flexores de cadera con un ritmo alto.",
    coachInstructions: "• Las rodillas deben subir hasta que el muslo quede paralelo al suelo en cada paso.\n\n• Mantén el torso erguido o ligeramente inclinado hacia adelante, nunca hacia atrás.\n\n• Coordina el braceo de forma enérgica (brazo opuesto a la rodilla que sube).\n\n• Toca el suelo mínimamente con el metatarso para mantener la velocidad reactiva.\n\n• Enfócate en mantener una frecuencia de pasos alta durante toda la serie.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "7d0bbbe6-955e-400b-beb9-d049d7bd3e70",
    name: "Talones al culo (Butt Kicks)",
    methodTypeCode: "activacion",
    equipmentCode: "undefined",
    description: "Carrera estática donde los talones buscan el contacto con los glúteos en cada paso. Estira dinámicamente los cuádriceps y activa los femorales mientras mantiene la frecuencia cardíaca elevada.",
    coachInstructions: "• Intenta que el talón toque realmente el glúteo en cada repetición.\n\n• Los muslos deben permanecer casi verticales, evitando que las rodillas suban adelante.\n\n• Mantén un ritmo rápido y fluido, rebotando sobre la parte delantera del pie.\n\n• Coordina el movimiento con un braceo ligero y relajado a los lados del torso.\n\n• Mantén el core firme para evitar que el cuerpo oscile excesivamente hacia adelante.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "27204d4f-5264-4b6c-bc2e-b8a790376667",
    name: "Cinta de correr",
    methodTypeCode: "maquinas_cardio",
    equipmentCode: "undefined",
    description: "Permite simular la marcha, el trote o la carrera en un entorno controlado. Su utilidad principal es la mejora de la capacidad aeróbica y el alto gasto calórico. Ofrece control exacto sobre la velocidad y la inclinación, facilitando entrenamientos de intervalos (HIIT) o de resistencia base.",
    coachInstructions: "• Mantén el torso erguido y evita mirar hacia tus pies para no perder el equilibrio.\n\n• Aterriza con la parte media del pie, evitando el impacto seco del talón contra la banda.\n\n• Avanzado: Trabaja la cadencia (pasos por minuto) para mejorar la eficiencia de carrera.\n\n• Contraproducente: En personas con lesiones agudas de rodilla o tobillo por el impacto repetitivo.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "2f450bdd-6271-464f-8ceb-cb8f0d04fcc6",
    name: "Bicicleta estática",
    methodTypeCode: "maquinas_cardio",
    equipmentCode: "undefined",
    description: "Ideal para el desarrollo de la resistencia cardiovascular con un impacto articular nulo. Se utiliza para el fortalecimiento de la musculatura inferior sin estrés óseo, rehabilitación de rodilla y protocolos de recuperación activa después de sesiones intensas de pesas.",
    coachInstructions: "• Ajusta la altura del sillín de modo que la pierna quede casi estirada (90-95%) en el punto bajo.\n\n• Mantén la columna alineada, evitando encorvar la espalda sobre el manillar.\n\n• Asegura que las rodillas sigan una línea recta y no se abran hacia los lados al pedalear.\n\n• Avanzado: Controla los vatios (potencia) para asegurar una intensidad de trabajo constante.\n\n• Avanzado: Realiza cambios de cadencia (RPM) para desafiar el sistema anaeróbico.\n\n• Contraproducente: En casos de lumbalgia crónica si la postura es demasiado inclinada o sillín mal ajustado.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "099afe7a-2a82-4fea-86ce-9f1efc26ca41",
    name: "Elíptica",
    methodTypeCode: "maquinas_cardio",
    equipmentCode: "undefined",
    description: "Combina el movimiento de la carrera con el del esquí de fondo, permitiendo un trabajo de cuerpo completo (brazos y piernas) con impacto cero. Es útil para quemar calorías protegiendo las articulaciones y para mejorar la coordinación intermuscular.",
    coachInstructions: "• Mantén toda la planta del pie en contacto con el pedal; no te apoyes solo en las punteras.\n\n• Sujeta los brazos móviles para involucrar activamente la musculatura del torso y espalda.\n\n• Mantén el abdomen contraído para evitar el balanceo excesivo de la cadera.\n\n• Avanzado: Utiliza la marcha atrás para enfatizar el trabajo de los isquiotibiales y glúteos.\n\n• Avanzado: Ajusta la resistencia para que el movimiento sea fluido y no por inercia de la máquina.\n\n• Contraproducente: Si se sufre de entumecimiento en los pies (parestesia) por presión prolongada.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "cd6bea12-a4e4-44e7-b827-bf7a4a1c4673",
    name: "Escaladora (Stairmaster)",
    methodTypeCode: "maquinas_cardio",
    equipmentCode: "undefined",
    description: "Simula la subida de peldaños infinita. Su utilidad reside en la alta activación del glúteo y cuádriceps, además de ser una herramienta de acondicionamiento metabólico muy exigente. Mejora la fuerza funcional de las piernas para actividades cotidianas.",
    coachInstructions: "• Apoya el pie completo en el escalón; evita subir siempre de puntillas para no fatigar el gemelo.\n\n• Mantén el torso vertical; no te apoyes con todo el peso en los pasamanos laterales.\n\n• Mira siempre al frente para asegurar la estabilidad y una respiración profunda.\n\n• Avanzado: Sube peldaños de dos en dos para aumentar la demanda mecánica en el glúteo.\n\n• Avanzado: Suelta las manos del soporte para desafiar el equilibrio y la estabilidad del core.\n\n• Contraproducente: En patologías de menisco o condromalacia rotuliana avanzada por la flexión profunda.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "87a98f49-6c88-4c59-98fb-07aa8fa224a0",
    name: "Air Bike (Assault Bike)",
    methodTypeCode: "maquinas_cardio",
    equipmentCode: "undefined",
    description: "Utiliza la resistencia del aire (a más velocidad, más resistencia). Es la herramienta definitiva para el acondicionamiento metabólico y el trabajo de potencia anaeróbica. Útil para elevar las pulsaciones al máximo en tiempos muy reducidos.",
    coachInstructions: "• Coordina el empuje y la tracción de los brazos con el pedaleo de las piernas.\n\n• Mantén la cabeza alta y evita balancear el cuerpo de lado a lado durante el sprint.\n\n• Ajusta el asiento de modo que los brazos no queden totalmente bloqueados al empujar.\n\n• Avanzado: Realiza intervalos de máxima potencia (Tabata) para maximizar el consumo de oxígeno.\n\n• Avanzado: Enfócate en la respiración rítmica para evitar la fatiga prematura por falta de aire.\n\n• Contraproducente: En personas con problemas cardíacos no diagnosticados debido a la altísima intensidad.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "ee52970d-b867-4846-a602-09c2e6222339",
    name: "SkiErg",
    methodTypeCode: "maquinas_cardio",
    equipmentCode: "undefined",
    description: "Simula el movimiento del esquí nórdico. Útil para trabajar la potencia de la cadena anterior (abdomen) y la resistencia de hombros y brazos, mientras genera una demanda cardiovascular masiva sin impacto en las piernas.",
    coachInstructions: "• Inicia el tirón desde arriba flexionando ligeramente las rodillas para usar el peso corporal.\n\n• Termina el movimiento con los brazos extendidos hacia atrás (tríceps) y cerca de los muslos.\n\n• Mantén el core firme para evitar que la espalda lumbar sufra con el tirón vertical.\n\n• Avanzado: Mantén una cadencia de tirones constante para optimizar la eficiencia del flujo de aire.\n\n• Avanzado: Varía entre la técnica de brazos simultáneos y alternos para cambiar el estímulo.\n\n• Contraproducente: En lesiones de manguito rotador o tendinitis de hombro en fase aguda.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "827e882f-de5a-45a0-bd6e-70f4c34d459b",
    name: "Bicicleta de ciclo indoor",
    methodTypeCode: "maquinas_cardio",
    equipmentCode: "undefined",
    description: "Diseñada para simular el ciclismo de carretera. Su utilidad principal es el entrenamiento de alta intensidad (HIIT) y la mejora de la potencia aeróbica/anaeróbica. A diferencia de la estática convencional, permite pedalear de pie, lo que involucra más al core y glúteos bajo una resistencia de inercia fija.",
    coachInstructions: "• Ajusta el manillar y el sillín para que la rodilla no sobrepase el eje del pedal en la fase horizontal.\n\n• Mantén una cadencia fluida; evita que el volante de inercia \"te lleve\" las piernas sin control.\n\n• Al pedalear de pie, mantén el peso sobre los pedales y no te apoyes excesivamente en el manillar.\n\n• Avanzado: Utiliza el freno de emergencia para intervalos de potencia máxima con seguridad.\n\n• Avanzado: Mantén el core activado para evitar el balanceo lateral del tronco en sprints.\n\n• Contraproducente: En personas con problemas de próstata o suelo pélvico si el sillín no es adecuado, o lesiones lumbares por posturas agresivas.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "d2ee1a1e-9af2-4341-ab04-090eb75336de",
    name: "Máquina de remo",
    methodTypeCode: "maquinas_cardio",
    equipmentCode: "undefined",
    description: "Es una de las herramientas de acondicionamiento físico más completas. Su utilidad radica en la combinación de fuerza explosiva de piernas y tracción de espalda. Es excelente para el gasto calórico masivo y la mejora de la resistencia muscular en toda la cadena posterior.",
    coachInstructions: "• Empuja primero con las piernas, luego inclina el torso y finalmente tira con los brazos.\n\n• Mantén los talones apoyados en el soporte durante la mayor parte del empuje inicial.\n\n• No permitas que la espalda se encorve al ir a buscar el agarre en la parte delantera.\n\n• Avanzado: Enfócate en la potencia de la palada medida en tiempo por 500 metros (Split).\n\n• Avanzado: Controla el retorno (recuperación) para que sea el doble de lento que el empuje.\n\n• Contraproducente: En personas con hernias discales o dolor lumbar agudo debido a la flexión repetitiva del tronco.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "695315ff-8bd8-48a8-8731-06684872d696",
    name: "Arc Trainer",
    methodTypeCode: "maquinas_cardio",
    equipmentCode: "undefined",
    description: "A diferencia de la elíptica, esta máquina tiene una trayectoria en forma de arco. Su utilidad es maximizar el reclutamiento de glúteos y cuádriceps mientras reduce la presión en la articulación de la rodilla y cadera. Es ideal para quemar calorías con una percepción de esfuerzo menor.",
    coachInstructions: "• Asegúrate de que los pies estén centrados en los pedales para que el movimiento sea fluido.\n\n• Utiliza los agarres móviles para aumentar la demanda metabólica y el trabajo de brazos.\n\n• Mantén la columna erguida y evita \"botar\" sobre la máquina durante el ejercicio.\n\n• Avanzado: Ajusta la inclinación alta para priorizar glúteos o baja para enfocar cuádriceps.\n\n• Avanzado: Realiza intervalos de alta resistencia para trabajar la fuerza-resistencia de piernas.\n\n• Contraproducente: En casos de bursitis de cadera activa debido al amplio rango de movimiento lateral/diagonal.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "66d89170-3bad-4e0c-b043-ab19a2230159",
    name: "Versa Climber",
    methodTypeCode: "maquinas_cardio",
    equipmentCode: "undefined",
    description: "Simula el movimiento de escalada vertical en una pared. Su utilidad es el acondicionamiento total del cuerpo bajo un plano vertical, lo que eleva las pulsaciones más rápido que casi cualquier otra máquina. Mejora la coordinación cruzada (brazo-pierna opuesta) y la fuerza del core.",
    coachInstructions: "• Mantén una postura vertical; no permitas que el glúteo sobresalga hacia atrás fuera del eje.\n\n• Coordina el movimiento: cuando una mano sube, la pierna opuesta también debe hacerlo.\n\n• Utiliza pasos cortos si buscas velocidad, o largos para mayor demanda de fuerza.\n\n• Avanzado: Realiza sprints de 30 segundos sin apoyo de manos para un reto de core extremo.\n\n• Avanzado: Enfócate en el empuje del pedal hacia abajo para maximizar la potencia del glúteo.\n\n• Contraproducente: En personas con vértigo, problemas graves de hombro (impingement) o inestabilidad de tobillo.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "eaaf0fc7-9d8f-46d3-a533-ffe3168eda91",
    name: "Continuo extensivo",
    methodTypeCode: "continuo_extensivo",
    equipmentCode: "undefined",
    description: "Trabajo de larga duración a intensidad baja (60-70% FC máx). Su utilidad es la creación de una base aeróbica sólida, mejora de la capilarización muscular y eficiencia en el uso de grasas como sustrato energético principal.",
    coachInstructions: "• Ejemplo 1: 60 min de carrera continua a un ritmo suave que permita respirar exclusivamente por la nariz.\n\n• Ejemplo 2: 90 min de ciclismo en terreno llano manteniendo una cadencia constante y sin picos de esfuerzo.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "29d85c1f-edcf-4ac6-9d5b-6e2e4bbc031e",
    name: "Continuo intensivo",
    methodTypeCode: "continuo_intensivo",
    equipmentCode: "undefined",
    description: "Trabajo de media-larga duración a intensidad moderada-alta (75-85% FC máx). Permite mejorar el metabolismo del glucógeno y la eficiencia cardiovascular a ritmos de competición. Aumenta el volumen sistólico del corazón.",
    coachInstructions: "• Ejemplo 1: 30 min de carrera a un ritmo \"vivo\" (cerca del ritmo de 10k), donde la conversación sea difícil.\n\n• Ejemplo 2: 40 min de remo manteniendo un ritmo de palada constante y exigente (Split estable).",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "8f6bd57f-6ef6-47bb-b07a-5586158a8a27",
    name: "Intervalos aeróbicos extensivos",
    methodTypeCode: "intervalos_aerobicos_extensivos",
    equipmentCode: "undefined",
    description: "Series largas (de 3 a 10 min) a intensidad moderada-alta con descansos cortos. Permite mejorar la capacidad aeróbica y la capacidad de mantener ritmos sub-umbrales durante más tiempo sin acumular fatiga excesiva.",
    coachInstructions: "• Ejemplo 1: 4 series de 5 min de carrera al 80% de intensidad con 2 min de trote muy suave de recuperación.\n\n• Ejemplo 2: 3 series de 8 min de elíptica a resistencia alta con 3 min de pedaleo sin carga entre ellas.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "41523738-237f-43b1-a0a4-44bc608f8c72",
    name: "Intervalos intensivos",
    methodTypeCode: "intervalos_intensivos",
    equipmentCode: "undefined",
    description: "Series de duración media (1 a 3 min) a intensidad alta (85-95% FC máx). Su utilidad principal es la mejora del VO2 Máx (consumo de oxígeno) y la potencia aeróbica, obligando al corazón a trabajar a su máximo rendimiento.",
    coachInstructions: "• Ejemplo 1: 6 series de 2 min de sprint en cuesta o cinta con 2 min de descanso total entre cada una.\n\n• Ejemplo 2: 8 series de 500m en remo a ritmo máximo con 90s de descanso estático.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "47e957d5-fd95-4d0a-8337-6957d522254f",
    name: "Tempo / Umbral",
    methodTypeCode: "tempo_umbral",
    equipmentCode: "undefined",
    description: "Carrera constante al ritmo exacto del umbral de lactato (punto donde el cuerpo empieza a acumular ácido láctico más rápido de lo que puede eliminarlo). Mejora la tolerancia a la fatiga y permite correr más rápido durante más tiempo.",
    coachInstructions: "• Ejemplo 1: 20 min de carrera al ritmo más alto que puedas mantener de forma constante sin \"explotar\".\n\n• Ejemplo 2: 2 bloques de 10 min a ritmo de umbral con 3 min de recuperación activa entre ellos.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "5995f068-37bd-435d-849a-1ecae4bd3b24",
    name: "HIIT corto",
    methodTypeCode: "hiit_corto",
    equipmentCode: "undefined",
    description: "Esfuerzos de muy corta duración (10 a 30 seg) a intensidad máxima o supramáxima. Mejora la potencia neuromuscular, la capacidad de aceleración y la resíntesis de fosfocreatina. Ideal para quemar grasa y ganar potencia.",
    coachInstructions: "• Ejemplo 1: 15 series de 15s de sprint máximo / 15s de descanso total (Ratio 1:1).\n\n• Ejemplo 2: 12 series de 20s de Air Bike a máxima potencia / 40s de pedaleo muy suave.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "ade93589-0689-4c68-9e77-40f37afb3b56",
    name: "HIIT largo",
    methodTypeCode: "hiit_largo",
    equipmentCode: "undefined",
    description: "Intervalos de alta intensidad que duran entre 2 y 4 minutos. A diferencia del corto, este método busca mantener una frecuencia cardíaca elevada durante más tiempo, maximizando las adaptaciones centrales (corazón y pulmones).",
    coachInstructions: "• Ejemplo 1: 4 series de 4 min al 90-95% FC máx con 3 min de recuperación activa entre series.\n\n• Ejemplo 2: 5 series de 3 min en elíptica a máxima resistencia con 2 min de descanso caminando.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "70ddb095-933c-4b6e-a186-bca18aef5c87",
    name: "Anaeróbico láctico",
    methodTypeCode: "anaerobico_lactico",
    equipmentCode: "undefined",
    description: "Esfuerzos de máxima intensidad de 30s a 2 min donde se genera una gran acumulación de lactato. Su utilidad es mejorar la tolerancia al \"quemazón\" muscular y la capacidad del cuerpo para trabajar en condiciones de acidez extrema.",
    coachInstructions: "• Ejemplo 1: 3 series de 400 metros lisos al 100% de esfuerzo con 5-8 min de descanso para asegurar recuperación parcial.\n\n• Ejemplo 2: 4 series de 1 min de Burpees a máxima velocidad con 3 min de descanso total.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "815ca0f3-434b-44d4-9ce7-6cdb2b6ce760",
    name: "Fartlek",
    methodTypeCode: "fartlek",
    equipmentCode: "undefined",
    description: "\"Juego de velocidades\" que combina diferentes intensidades y duraciones de forma irregular. Mejora la capacidad de respuesta ante cambios de ritmo y la recuperación activa en movimiento.",
    coachInstructions: "• Ejemplo 1: Carrera de 30 min: alterna 2 min fuertes, 1 min suave, 30s sprint, 2 min suaves de forma aleatoria.\n\n• Ejemplo 2: 20 min de natación alternando largos a máxima velocidad con largos de recuperación según sensaciones.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
];
