export const EXERCISE_EQUIPMENT_V1 = [
  { code: 'undefined', label: 'Sin definir', sortOrder: 0, isDefault: true },
  { code: 'barbell', label: 'Barra', sortOrder: 1, isDefault: false },
  { code: 'dumbbell', label: 'Mancuernas', sortOrder: 2, isDefault: false },
  { code: 'cable', label: 'Polea', sortOrder: 3, isDefault: false },
  { code: 'machine', label: 'Maquina', sortOrder: 4, isDefault: false },
  { code: 'bodyweight', label: 'Peso Corporal', sortOrder: 5, isDefault: false },
  { code: 'band', label: 'Banda elastica', sortOrder: 6, isDefault: false },
  { code: 'fitball', label: 'Fitball', sortOrder: 7, isDefault: false },
  { code: 'medicine_ball', label: 'Balon medicinal', sortOrder: 8, isDefault: false },
  { code: 'kettlebell', label: 'Kettlebell', sortOrder: 9, isDefault: false },
  { code: 'hand_gripper', label: 'Hand Gripper', sortOrder: 10, isDefault: false },
  { code: 'plyo_box', label: 'Cajon pliometrico', sortOrder: 11, isDefault: false },
  { code: 'mini_hurdles', label: 'Micro-vallas', sortOrder: 12, isDefault: false },
  { code: 'hurdles', label: 'Vallas', sortOrder: 13, isDefault: false },
  { code: 'low_step', label: 'Escalon bajo', sortOrder: 14, isDefault: false },
  { code: 'wall', label: 'Pared', sortOrder: 15, isDefault: false },
  { code: 'fixed_bar',   label: 'Barra fija',  sortOrder: 16, isDefault: false },
  { code: 'foam_roller', label: 'Foam Roller', sortOrder: 17, isDefault: false },
  { code: 'stick',       label: 'Palo',        sortOrder: 18, isDefault: false },
  { code: 'fins',        label: 'Aletas',      sortOrder: 19, isDefault: false },
  { code: 'paddles',     label: 'Palas',       sortOrder: 20, isDefault: false },
  { code: 'pull_buoy',   label: 'Pull-buoy',   sortOrder: 21, isDefault: false },
  { code: 'kickboard',   label: 'Tabla',       sortOrder: 22, isDefault: false },
  { code: 'sled',        label: 'Trineo',      sortOrder: 23, isDefault: false },
];
