export type PlioExerciseSeed = {
  id: string;
  name: string;
  plioTypeCode: string;
  equipmentCode: string;
  description: string | null;
  coachInstructions: string | null;
  youtubeUrl: string;
};

export const PLIO_EXERCISES_V1: PlioExerciseSeed[] = [
  {
    id: "8fc8f40c-278a-426a-aa46-613e972745ea",
    name: "Pogo Jumps (tobillos)",
    plioTypeCode: "extensive",
    equipmentCode: "undefined",
    description: "Saltos verticales rítmicos realizados exclusivamente mediante el juego del tobillo. El objetivo es minimizar el tiempo de contacto con el suelo y maximizar la elasticidad del tendón de Aquiles sin flexionar las rodillas.",
    coachInstructions: "• Mantén las rodillas bloqueadas o con una flexión mínima e imperceptible.\n\n• Imagina que el suelo quema; rebota lo más rápido posible tras el contacto.\n\n• Los brazos deben acompañar el ritmo para ayudar a la estabilidad vertical.\n\n• Enfócate en mantener los pies activos (en \"flex\") mientras estás en el aire.\n\n• Realiza una serie continua buscando la máxima rigidez del tobillo en cada rebote.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "31cc2c8f-aa81-41f7-8904-36c0c084c5c1",
    name: "Lateral Pogo Jumps",
    plioTypeCode: "extensive",
    equipmentCode: "undefined",
    description: "Similar a los Pogo Jumps pero desplazándose lateralmente de forma rítmica sobre una línea imaginaria. Trabaja la estabilidad lateral del tobillo y la reactividad de los tendones en el plano frontal.",
    coachInstructions: "• Salta de lado a lado manteniendo los pies juntos y las rodillas rígidas.\n\n• El tiempo de contacto con el suelo debe ser igual de corto que en la versión vertical.\n\n• Mantén el torso erguido y evita inclinaciones laterales del tronco.\n\n• Utiliza el metatarso para el rebote; el talón no debe tocar el suelo con fuerza.\n\n• Busca una cadencia constante y fluida durante toda la ejecución.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "e83aa77b-0a44-4e3d-9092-349632791b71",
    name: "A-Skips",
    plioTypeCode: "extensive",
    equipmentCode: "undefined",
    description: "Salto rítmico coordinado donde se eleva una rodilla hacia el pecho mientras el brazo contrario acompaña el movimiento. Es un pilar de la técnica de carrera que mejora la coordinación y la elasticidad cíclica.",
    coachInstructions: "• La rodilla debe subir de forma explosiva hasta quedar paralela al suelo.\n\n• El pie de apoyo debe realizar un doble contacto rápido y elástico en el sitio.\n\n• Mantén el torso erguido y los codos flexionados a 90 grados sincronizados.\n\n• Ataca el suelo con el metatarso justo debajo de tu centro de gravedad.\n\n• Exagera el movimiento de brazos para facilitar la elevación de la cadera.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "f605227e-1d3a-4f60-843a-772774ac1d16",
    name: "Patinadores rítmicos",
    plioTypeCode: "extensive",
    equipmentCode: "undefined",
    description: "Saltos laterales cortos realizados de forma fluida y continua. A diferencia de la versión intensiva, aquí se busca el ritmo y la coordinación lateral más que la distancia máxima de salto.",
    coachInstructions: "• Realiza el salto de lado a lado buscando un aterrizaje suave y controlado.\n\n• La pierna trasera debe cruzar ligeramente por detrás para equilibrar el peso.\n\n• Mantén el centro de gravedad bajo y las rodillas preparadas para el rebote.\n\n• Coordina el braceo lateral para generar inercia y estabilidad en el cambio.\n\n• Enfócate en la fluidez del movimiento; no debe haber pausas entre saltos.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "ce34a8c4-7523-4335-a06f-37cedcfe0a45",
    name: "Low Box Taps",
    plioTypeCode: "extensive",
    equipmentCode: "low_step",
    description: "Toques de puntera rápidos y alternos sobre un escalón de baja altura (10-15 cm). Es un ejercicio de agilidad de pies que eleva la frecuencia de pasos y mejora la reactividad neuromuscular.",
    coachInstructions: "• Solo la punta del pie debe rozar el escalón de forma rápida y ligera.\n\n• Mantén una frecuencia de pies lo más alta posible sin perder el ritmo.\n\n• El torso debe permanecer estable; evita balanceos innecesarios de hombros.\n\n• Utiliza un braceo corto y rápido para sincronizar la velocidad de piernas.\n\n• Mantén la mirada un paso por delante para asegurar la precisión del contacto.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "7883c1a8-4fdb-42bb-b389-c7f3d228171c",
    name: "Hops sobre micro-vallas",
    plioTypeCode: "extensive",
    equipmentCode: "mini_hurdles",
    description: "Saltos continuos y rápidos sobre una serie de vallas pequeñas. El énfasis está en el ritmo constante y en la capacidad de los tendones para absorber y liberar energía de forma cíclica.",
    coachInstructions: "• Mantén los saltos cortos y elásticos; no busques ganar demasiada altura.\n\n• Ataca cada valla con la punta de los pies y rebota inmediatamente.\n\n• Los brazos deben trabajar en bloque para estabilizar el salto vertical.\n\n• Asegura que el tiempo que pasas en el suelo sea el mínimo posible entre vallas.\n\n• Mantén el core firme para evitar que el cuerpo se incline hacia adelante.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "69a38855-503c-4613-81bc-a0906de4c05d",
    name: "Saltos de tijera rítmicos",
    plioTypeCode: "extensive",
    equipmentCode: "undefined",
    description: "Saltos rápidos alternando la posición de los pies (uno adelante y otro atrás) sobre una línea. Mejora la coordinación de piernas y la reactividad del tren inferior en un plano anteroposterior.",
    coachInstructions: "• Alterna los pies de forma explosiva manteniendo la cadera a la misma altura.\n\n• El contacto con el suelo debe ser reactivo, usando principalmente la puntera.\n\n• Coordina el braceo opuesto a la pierna adelantada como si estuvieras corriendo.\n\n• Mantén el abdomen activo para evitar oscilaciones excesivas del torso.\n\n• Realiza el ejercicio buscando la máxima velocidad de pies que puedas controlar.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "d42ca28b-dd3c-445c-b95e-55b00254b451",
    name: "Broad Jump (Salto de longitud)",
    plioTypeCode: "intensive",
    equipmentCode: "undefined",
    description: "Salto horizontal desde parado buscando la máxima distancia posible. Requiere una triple extensión explosiva (tobillo, rodilla, cadera) y una recepción estable para frenar la inercia.",
    coachInstructions: "• Inicia el salto llevando los brazos atrás y flexionando ligeramente la cadera.\n\n• Lanza los brazos hacia adelante con potencia para generar inercia de despegue.\n\n• Extiende el cuerpo por completo en el aire antes de buscar el aterrizaje.\n\n• Recepciona con ambos pies a la vez, amortiguando la caída con la cadera.\n\n• Mantén el estatismo final; no des pasos adicionales tras tocar el suelo.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "52312450-5fa6-468a-8b09-b2b6869ada5f",
    name: "Triple salto (sin material)",
    plioTypeCode: "intensive",
    equipmentCode: "undefined",
    description: "Secuencia encadenada de tres saltos máximos (pata coja, zancada y salto a pies juntos). Es uno de los ejercicios de mayor demanda elástica y coordinativa para el tren inferior.",
    coachInstructions: "• Cada salto de la secuencia debe buscar la máxima distancia horizontal posible.\n\n• Mantén el torso erguido para no perder el equilibrio entre los contactos.\n\n• Ataca el suelo con fuerza para convertir la caída en el siguiente despegue.\n\n• Coordina los brazos de forma enérgica para mantener la velocidad de vuelo.\n\n• El último salto debe finalizar con una recepción estable sobre ambos pies.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "429aa0b4-6fea-4d7f-94f9-09282dbbbe2c",
    name: "Depth Jump (Salto de caída)",
    plioTypeCode: "intensive",
    equipmentCode: "plyo_box",
    description: "El ejercicio \"rey\". Consiste en dejarse caer de un cajón y, nada más tocar el suelo, saltar verticalmente con la máxima potencia posible. Maximiza el ciclo estiramiento-acortamiento.",
    coachInstructions: "• Déjate caer del cajón; no saltes hacia afuera, simplemente \"déjate ir\".\n\n• El contacto con el suelo debe ser lo más corto y explosivo posible.\n\n• Salta hacia arriba buscando tocar el techo en cuanto notes el suelo bajo tus pies.\n\n• Evita que los talones toquen el suelo con fuerza; rebota con el metatarso.\n\n• La altura del cajón debe permitir un rebote instantáneo, no una caída pesada.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "eadfc3aa-41bc-4cd0-93cd-b0426c82bc53",
    name: "Single Leg Broad Jump",
    plioTypeCode: "intensive",
    equipmentCode: "undefined",
    description: "Salto de longitud realizado a una sola pierna. Exige una potencia unilateral máxima y una gran capacidad de estabilización de la rodilla y el tobillo durante la recepción.",
    coachInstructions: "• Impúlsate con fuerza usando únicamente la pierna de apoyo y el braceo.\n\n• Busca aterrizar de forma estable; puedes usar la otra pierna para equilibrarte al final.\n\n• Mantén la rodilla de despegue alineada con el pie; evita que colapse hacia adentro.\n\n• Realiza una fase excéntrica controlada al preparar el salto para cargar el músculo.\n\n• Enfócate en la distancia recorrida sin comprometer la seguridad del aterrizaje.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "264a8508-25b7-4589-9703-3c03dba81929",
    name: "Jump to Landing",
    plioTypeCode: "intensive",
    equipmentCode: "undefined",
    description: "Salto vertical máximo donde el objetivo principal no es la altura, sino la recepción perfecta (\"stick\"). Se debe quedar totalmente inmóvil al tocar el suelo, absorbiendo toda la energía.",
    coachInstructions: "• Salta con potencia y prepara el cuerpo en el aire para el contacto con el suelo.\n\n• Al aterrizar, flexiona caderas y rodillas para absorber el impacto en silencio.\n\n• Mantén la posición de recepción durante 2 segundos sin realizar micro-ajustes.\n\n• Asegura que las rodillas no se hundan hacia adentro al tocar el piso.\n\n• La espalda debe permanecer neutra y el pecho alto durante el frenado.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "413f32c8-d73c-4ddd-b1fd-b038095e22de",
    name: "Depth Jump a Box Jump",
    plioTypeCode: "intensive",
    equipmentCode: "plyo_box",
    description: "Combinación de caída desde un cajón pequeño y salto inmediato para subir a un cajón más alto frente a ti. Entrena la reactividad y la transferencia de fuerza vertical.",
    coachInstructions: "• Minimiza el tiempo en el suelo entre la caída del primer cajón y el salto al segundo.\n\n• Ataca el suelo con agresividad para disparar el cuerpo hacia la plataforma superior.\n\n• Aterriza en el cajón alto de forma suave, buscando el centro de la base.\n\n• Mantén la mirada en el objetivo (el segundo cajón) durante todo el vuelo.\n\n• Extiende la cadera por completo una vez estés arriba del cajón final.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "7d363ff9-f10e-4d80-8ecf-ea435ba8f0e6",
    name: "Lateral Box Jump",
    plioTypeCode: "intensive",
    equipmentCode: "plyo_box",
    description: "Salto lateral explosivo para subir al cajón. A diferencia del salto frontal, este trabaja la potencia en el plano lateral, involucrando más al glúteo medio y los aductores.",
    coachInstructions: "• Colócate de lado al cajón y salta lateralmente usando ambos pies.\n\n• Coordina el balanceo de los brazos lateralmente para facilitar el ascenso.\n\n• Recepciona sobre el cajón con control, evitando que los pies resbalen lateralmente.\n\n• Baja del cajón de un paso, no saltando hacia atrás para evitar lesiones.\n\n• Asegura que el cajón sea estable y tenga una superficie antideslizante.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "c30b1f8d-b91d-4fbd-9ba5-e01b104771bc",
    name: "Approach Box Jump",
    plioTypeCode: "intensive",
    equipmentCode: "plyo_box",
    description: "Salto al cajón realizando una carrera previa de 2 o 3 pasos. La velocidad de aproximación se convierte en energía elástica para alcanzar una altura de salto muy superior a la estática.",
    coachInstructions: "• Sincroniza el último paso (paso de bloqueo) para convertir la velocidad en altura.\n\n• Los brazos deben subir con violencia hacia el techo en el momento del despegue.\n\n• Busca la máxima flexión de cadera en el aire para aterrizar alto en el cajón.\n\n• No permitas que la inercia de la carrera te desplace más allá del centro del cajón.\n\n• Mantén el core firme para absorber la gran fuerza reactiva del despegue.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "00b8080c-dd7f-4f1b-8faa-d4a4ec58b0e3",
    name: "Hurdle Hops (Vallas altas)",
    plioTypeCode: "intensive",
    equipmentCode: "hurdles",
    description: "Saltos verticales sobre vallas de altura considerable. Exige una gran potencia de despegue y una rápida elevación de rodillas al pecho para superar el obstáculo en el aire.",
    coachInstructions: "• Salta buscando \"flotar\" sobre la valla con la máxima elevación de cadera.\n\n• Lleva las rodillas hacia el pecho de forma explosiva mientras superas la valla.\n\n• Ataca el suelo tras cada valla para rebotar inmediatamente hacia la siguiente.\n\n• Mantén el torso erguido; no te encorves para intentar pasar las piernas.\n\n• El braceo debe ser amplio y potente para ayudar a la suspensión del cuerpo.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "600b9e21-ab23-48f0-b731-d2cd674dee70",
    name: "Lateral Hurdle Hops",
    plioTypeCode: "intensive",
    equipmentCode: "hurdles",
    description: "Saltos laterales potentes sobre vallas de altura media-alta. Es un ejercicio de gran demanda excéntrica que fortalece la estabilidad de rodilla contra fuerzas laterales.",
    coachInstructions: "• Salta de lado superando la valla con ambos pies al mismo tiempo.\n\n• Mantén la cadera mirando al frente; evita rotar el cuerpo durante el salto lateral.\n\n• La recepción debe ser elástica para permitir el salto de vuelta inmediato.\n\n• Utiliza los brazos como balancín para mantener el equilibrio en el aire.\n\n• Asegura que el aterrizaje sea estable antes de iniciar el siguiente salto lateral.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "06f69d59-ab92-4d20-b5d0-edab1397bd73",
    name: "Med Ball Chest Pass",
    plioTypeCode: "intensive",
    equipmentCode: "medicine_ball",
    description: "Lanzamiento explosivo del balón desde el pecho contra una pared o a un compañero. El objetivo es la máxima velocidad de salida de la carga, trabajando la potencia del pectoral y tríceps.",
    coachInstructions: "• Empuja el balón con ambas manos de forma simultánea y explosiva.\n\n• Extiende los brazos por completo siguiendo la trayectoria del balón.\n\n• No realices una carga excesiva hacia atrás; busca un movimiento corto y reactivo.\n\n• Involucra ligeramente el core para transferir la fuerza desde el suelo.\n\n• Realiza el lanzamiento buscando que el balón rebote con fuerza en la pared.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "c37e8553-9639-4960-aa1f-28703114be01",
    name: "Overhead Med Ball Throw",
    plioTypeCode: "intensive",
    equipmentCode: "medicine_ball",
    description: "Lanzamiento del balón por encima de la cabeza hacia atrás buscando la distancia máxima. Involucra toda la cadena posterior en una extensión explosiva global.",
    coachInstructions: "• Inicia el movimiento con una flexión de cadera y rodillas, llevando el balón abajo.\n\n• Lanza el balón hacia atrás y arriba con una triple extensión violenta del cuerpo.\n\n• Suelta el balón en el punto de máxima extensión para optimizar la parábola.\n\n• Sigue el balón con la mirada solo después de haberlo soltado para proteger el cuello.\n\n• Mantén los pies anclados al suelo para transferir toda la potencia a la carga.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "dfa663a3-1bd1-4dee-a000-c58ebcd7c1b9",
    name: "Rotational Med Ball Throw",
    plioTypeCode: "intensive",
    equipmentCode: "medicine_ball",
    description: "Lanzamiento lateral del balón contra una pared buscando la máxima rotación explosiva del tronco. Trabaja la potencia de los oblicuos y la transferencia de fuerza cadera-tronco.",
    coachInstructions: "• Colócate de lado a la pared y lanza el balón mediante un giro rápido de cintura.\n\n• Pivotar sobre el pie trasero permite liberar la cadera y generar más potencia.\n\n• Mantén los brazos casi estirados para aumentar el brazo de palanca al lanzar.\n\n• Atrapa el balón en el rebote y aprovecha la inercia para la siguiente repetición.\n\n• Enfócate en la velocidad de rotación; el movimiento debe ser como un látigo.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "c6172249-e1e3-42af-b495-feb077804761",
    name: "Bounds (Zancadas en vuelo)",
    plioTypeCode: "intensive",
    equipmentCode: "undefined",
    description: "Saltos alternos de pierna a pierna buscando cubrir la mayor distancia posible en cada zancada, con un tiempo de vuelo prolongado. Es \"correr saltando\" con máxima potencia.",
    coachInstructions: "• Impúlsate con fuerza hacia adelante y arriba, buscando \"flotar\" en el aire.\n\n• Mantén la rodilla delantera alta y el pie de vuelo activo durante la suspensión.\n\n• Ataca el suelo con el metatarso para convertir la caída en el siguiente despegue.\n\n• El braceo debe ser exagerado y potente para coordinar la zancada larga.\n\n• Intenta mantener una línea de desplazamiento recta y estable sin oscilaciones.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "77f83ea1-3a95-4170-a3a2-50d8f08815bb",
    name: "Single-Leg Hops",
    plioTypeCode: "intensive",
    equipmentCode: "undefined",
    description: "Saltos rítmicos y potentes sobre una sola pierna buscando ganar altura o distancia. Exige una fuerza reactiva unilateral extrema y gran control del tobillo.",
    coachInstructions: "• Salta buscando la verticalidad o la horizontalidad según el objetivo del set.\n\n• Rebota de forma inmediata al tocar el suelo, minimizando el tiempo de contacto.\n\n• Usa la pierna libre para generar inercia mediante un movimiento de péndulo.\n\n• Mantén el core firme para evitar que el cuerpo se incline hacia el lado de apoyo.\n\n• Atrapa la caída con una flexión de rodilla controlada para proteger la articulación.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "f73106b7-7740-479d-8a82-9667c0803ef8",
    name: "Squat Jump with Tuck",
    plioTypeCode: "intensive",
    equipmentCode: "undefined",
    description: "Salto vertical máximo donde, en el punto más alto del vuelo, se llevan las rodillas rápidamente hacia el pecho. Requiere una potencia de despegue y una velocidad abdominal alta.",
    coachInstructions: "• Salta verticalmente con toda tu fuerza extendiendo cadera y rodillas.\n\n• En el aire, encoge las rodillas buscando que toquen tus manos o pecho.\n\n• Estira las piernas rápidamente antes de aterrizar para asegurar un contacto seguro.\n\n• Recepciona con el metatarso y amortigua la caída con una media sentadilla.\n\n• Evita redondear la espalda excesivamente al llevar las rodillas al pecho.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "223f2445-3c59-4799-956b-8c06e3975d8c",
    name: "Star Jumps",
    plioTypeCode: "intensive",
    equipmentCode: "undefined",
    description: "Salto explosivo donde, en el aire, se abren brazos y piernas formando una estrella. Combina la potencia vertical con la abducción rápida de extremidades.",
    coachInstructions: "• Salta desde una posición de media sentadilla lanzando el cuerpo hacia arriba.\n\n• Abre las extremidades al máximo en el punto más alto del salto.\n\n• Cierra el cuerpo rápidamente para aterrizar con los pies juntos y estables.\n\n• Mantén el torso erguido durante todo el vuelo de la \"estrella\".\n\n• Coordina la apertura y el cierre para que el movimiento sea simétrico y estético.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "43fc9bab-c5dd-4aeb-b574-d561954a839f",
    name: "Pike Jumps",
    plioTypeCode: "intensive",
    equipmentCode: "undefined",
    description: "Salto vertical intentando tocar las puntas de los pies con las manos en el aire, manteniendo las piernas totalmente estiradas. Exige gran potencia y flexibilidad dinámica.",
    coachInstructions: "• Salta verticalmente y eleva las piernas estiradas hacia adelante en el aire.\n\n• Busca el contacto de las manos con las punteras en el punto máximo de vuelo.\n\n• Baja las piernas con velocidad para aterrizar de forma segura sobre los dos pies.\n\n• Mantén el core muy fuerte para realizar la flexión de tronco necesaria.\n\n• Evita doblar las rodillas; la clave es la elevación de las piernas rectas.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "3698b4d9-c09e-4965-b149-4ef7331df256",
    name: "Seated Box Jump",
    plioTypeCode: "intensive",
    equipmentCode: "plyo_box",
    description: "Empiezas sentado en un cajón y saltas de forma explosiva a otro cajón frente a ti. Elimina el pre-estiramiento (impulso), obligando al músculo a generar fuerza desde cero.",
    coachInstructions: "• Siéntate con la espalda recta y los pies apoyados; no te balancees para saltar.\n\n• Despega del asiento mediante una extensión violenta de cadera y rodilla.\n\n• Lanza los brazos hacia arriba en el instante en que tus glúteos dejen el cajón.\n\n• Aterriza en el cajón de enfrente buscando estabilidad y una postura alta.\n\n• Este ejercicio entrena la potencia de arranque pura desde una posición estática.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "cdd7c08f-7cc2-46ff-b5a7-87498ab4905e",
    name: "Depth Broad Jump",
    plioTypeCode: "intensive",
    equipmentCode: "plyo_box",
    description: "Dejarse caer de un cajón y, al tocar el suelo, salir disparado hacia adelante en un salto de longitud máximo. Convierte la energía de la caída en distancia horizontal.",
    coachInstructions: "• Al tocar el suelo tras la caída, inclina el torso hacia adelante para saltar lejos.\n\n• El rebote debe ser instantáneo; no permitas que tus talones se \"claven\" en el suelo.\n\n• Lanza los brazos con fuerza hacia el frente para ganar inercia horizontal.\n\n• Busca una parábola de vuelo larga y aterriza de forma estable con ambos pies.\n\n• Mantén la tensión en el abdomen para resistir la gran fuerza de impacto.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "1a93a390-a127-4187-82be-23d708a9e5bd",
    name: "Box Drop to Vertical Jump",
    plioTypeCode: "intensive",
    equipmentCode: "plyo_box",
    description: "Dejarse caer del cajón y buscar la altura máxima de forma inmediata. A diferencia del anterior, aquí el vector de fuerza es puramente vertical tras el contacto con el suelo.",
    coachInstructions: "• Mantén el cuerpo erguido al caer para facilitar el salto vertical posterior.\n\n• Ataca el suelo con los pies paralelos y rebota buscando tocar el techo.\n\n• El tiempo en el suelo debe ser el mínimo posible para aprovechar la elasticidad.\n\n• Recepciona el salto final con suavidad, absorbiendo el impacto con las piernas.\n\n• No permitas que la caída sea demasiado alta si no puedes rebotar rápido.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "3003a8e3-76ef-45d1-96bd-29925482e867",
    name: "Power Drop",
    plioTypeCode: "intensive",
    equipmentCode: "medicine_ball",
    description: "Tumbado boca arriba, un compañero te suelta el balón, lo atrapas y lo lanzas hacia arriba lo más rápido posible. Es el equivalente al Depth Jump para el tren superior.",
    coachInstructions: "• Atrapa el balón con los brazos ligeramente flexionados para absorber la caída.\n\n• Lanza la carga hacia el techo de forma explosiva e inmediata tras el contacto.\n\n• Mantén la espalda lumbar pegada al suelo durante todo el lanzamiento.\n\n• Los hombros deben permanecer estables en el suelo; no los levantes al empujar.\n\n• Realiza el ejercicio con un compañero de confianza que suelte el balón con precisión.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "a6ef197a-afb3-4f43-90ac-18f99ad1914f",
    name: "Plyo Push-up",
    plioTypeCode: "intensive",
    equipmentCode: "undefined",
    description: "Flexión de brazos explosiva donde las manos (o todo el cuerpo) despegan del suelo. Entrena la potencia de empuje del pectoral y tríceps mediante el ciclo de estiramiento-acortamiento.",
    coachInstructions: "• Baja el pecho al suelo y empuja con toda tu fuerza para despegar las manos.\n\n• Puedes dar una palmada en el aire si tienes suficiente potencia de vuelo.\n\n• Recepciona con los codos ligeramente flexionados para amortiguar la caída.\n\n• Mantén el core bloqueado; el cuerpo debe subir y bajar como una tabla rígida.\n\n• Realiza repeticiones de alta calidad; detente cuando pierdas la altura del despegue.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
  {
    id: "70a06db1-7af0-4069-b12f-62c4f312da39",
    name: "Kneeling Med Ball Throw",
    plioTypeCode: "intensive",
    equipmentCode: "medicine_ball",
    description: "Lanzamiento de pecho desde posición de rodillas. Al eliminar la ayuda de las piernas, se obliga al tren superior y al core a generar toda la potencia del lanzamiento.",
    coachInstructions: "• Mantén el torso vertical y los glúteos contraídos para estabilizar la pelvis.\n\n• Lanza el balón con ambas manos desde el pecho buscando la pared frontal.\n\n• No te inclines hacia atrás para coger impulso; el movimiento nace de los brazos.\n\n• Sigue el lanzamiento con los brazos extendidos para asegurar la dirección.\n\n• Exhala con fuerza en el momento del empuje máximo del balón medicinal.",
    youtubeUrl: "https://youtube.com/shorts/ArzbfYT5MOw?feature=share",
  },
];
