import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  archivedButton: {
    alignItems: 'center',
    backgroundColor: '#f5f7fb',
    borderColor: '#d7dfe9',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    minWidth: 160,
    paddingHorizontal: 14,
  },
  archivedButtonDanger: {
    alignItems: 'center',
    backgroundColor: '#fff1f1',
    borderColor: '#ef4444',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    minWidth: 160,
    paddingHorizontal: 14,
  },
  archivedEmpty: { color: '#64748b', fontSize: 12, textAlign: 'center' },
  archivedItemSubtitle: { color: '#64748b', fontSize: 11 },
  archivedItemTitle: { color: '#0f172a', fontSize: 13, fontWeight: '700' },
  archivedLabel: { color: '#7f1d1d', fontSize: 12, fontWeight: '700' },
  archivedLabelNeutral: { color: '#475569', fontSize: 12, fontWeight: '700' },
  archivedLeft: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  archivedRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  board: { gap: 12 },
  chevron: { color: '#a0aec0', fontSize: 20, fontWeight: '700' },
  dragHandle: { color: '#c0cad8', fontSize: 14, marginRight: 8 },
  drawerClose: { color: '#94a3b8', fontSize: 24, lineHeight: 24 },
  drawerHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  drawerHeaderStart: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  drawerIcon: { color: '#1d4ed8', fontSize: 14, fontWeight: '700' },
  drawerIconShell: {
    alignItems: 'center',
    backgroundColor: '#e5edff',
    borderRadius: 12,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  drawerList: { gap: 10, marginTop: 14 },
  drawerSubtitle: {
    color: '#94a3b8',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  drawerTitle: { color: '#0f172a', fontSize: 24, fontWeight: '800' },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
  },
  headerTitle: { color: '#111827', fontSize: 33, fontWeight: '800' },
  iconShell: {
    alignItems: 'center',
    borderRadius: 12,
    height: 38,
    justifyContent: 'center',
    marginRight: 14,
    width: 38,
  },
  mainList: {
    backgroundColor: '#ffffff',
    borderColor: '#dce5f2',
    borderRadius: 20,
    borderWidth: 1,
    overflow: 'visible',
  },
  menuAction: { justifyContent: 'center', minHeight: 32, paddingHorizontal: 10 },
  menuActionLabel: { color: '#1f2937', fontSize: 12, fontWeight: '700' },
  menuButton: {
    alignItems: 'center',
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  menuLabel: { color: '#94a3b8', fontSize: 16, fontWeight: '700' },
  restoreButton: {
    alignItems: 'center',
    backgroundColor: '#eff6ff',
    borderColor: '#dbeafe',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 30,
    paddingHorizontal: 10,
  },
  restoreLabel: { color: '#1d4ed8', fontSize: 12, fontWeight: '700' },
  rowSubtitle: { color: '#64748b', fontSize: 12 },
  rowText: { flex: 1, gap: 2 },
  rowTitle: { color: '#0f172a', fontSize: 14, fontWeight: '800' },
});

export function drawerStyle(visible: boolean): React.CSSProperties {
  return {
    background: '#ffffff',
    borderLeft: '1px solid #dce5f2',
    borderRadius: '24px 0 0 24px',
    boxShadow: '-12px 0 36px rgba(15,23,42,0.2)',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    height: '100vh',
    maxWidth: '420px',
    padding: '24px 20px',
    position: 'fixed',
    right: 0,
    top: 0,
    transform: visible ? 'translateX(0)' : 'translateX(105%)',
    transition: 'transform 0.25s ease',
    width: 'min(90vw, 420px)',
    zIndex: 30,
  };
}

export const menuStyle: React.CSSProperties = {
  background: '#ffffff',
  border: '1px solid #dbe2ee',
  borderRadius: 10,
  boxShadow: '0 8px 18px rgba(15,23,42,0.12)',
  minWidth: 180,
  position: 'absolute',
  right: 36,
  top: 42,
  zIndex: 10,
};

export const menuStyleTop: React.CSSProperties = {
  ...menuStyle,
  bottom: 42,
  top: 'auto',
};

export const backdropStyle: React.CSSProperties = {
  background: 'rgba(10,18,35,0.42)',
  bottom: 0,
  left: 0,
  position: 'fixed',
  right: 0,
  top: 0,
  zIndex: 20,
};

export const rowStyle: React.CSSProperties = {
  alignItems: 'center',
  borderBottom: '1px solid #edf2f7',
  cursor: 'grab',
  display: 'flex',
  flexDirection: 'row',
  minHeight: 72,
  padding: '10px 14px',
  position: 'relative',
};
