import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  empty: {
    color: '#5d6f85',
    fontSize: 13,
  },
  filtersRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  headerRow: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'space-between',
    paddingRight: 8,
  },
  objectiveFilter: {
    backgroundColor: '#ffffff',
    borderColor: '#e3eaf5',
    borderRadius: 10,
    borderWidth: 1,
    color: '#4a5568',
    fontSize: 13,
    fontWeight: '600',
    flexBasis: 200,
    flexGrow: 1,
    height: 38,
    minWidth: 160,
    outlineColor: '#1c74e9',
    paddingHorizontal: 12,
  },
  searchInput: {
    backgroundColor: '#ffffff',
    borderColor: '#e3eaf5',
    borderRadius: 10,
    borderWidth: 1,
    color: '#475569',
    flexBasis: 200,
    flexGrow: 1,
    fontSize: 13,
    minWidth: 160,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  title: {
    color: '#0f172a',
    fontSize: 34,
    fontWeight: '800',
  },
});
