import type { CSSProperties } from 'react';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  archiveBox: {
    backgroundColor: '#fff5f5',
    borderColor: '#f2c9c9',
    borderRadius: 12,
    borderWidth: 1,
    marginTop: 6,
    padding: 10,
  },
  archiveButton: {
    alignItems: 'center',
    backgroundColor: '#d92d20',
    borderRadius: 10,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 14,
  },
  archiveLabel: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
  },
  archiveText: {
    color: '#7a1f1f',
    fontSize: 12,
    fontWeight: '700',
    flex: 1,
    marginRight: 10,
  },
  actions: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'flex-end',
    marginTop: 10,
  },
  avatarActions: {
    flexDirection: 'row',
    gap: 8,
    width: '100%',
  },
  avatarButton: {
    alignItems: 'center',
    backgroundColor: '#edf4ff',
    borderColor: '#d4e0f3',
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 10,
  },
  avatarFallback: {
    alignItems: 'center',
    backgroundColor: '#edf3fd',
    borderColor: '#d2dff2',
    borderRadius: 999,
    borderWidth: 1,
    height: 76,
    justifyContent: 'center',
    marginBottom: 10,
    width: 76,
  },
  avatarFallbackLabel: {
    color: '#3c506b',
    fontSize: 14,
    fontWeight: '800',
  },
  avatarImage: {
    alignSelf: 'center',
    borderRadius: 999,
    height: 76,
    marginBottom: 10,
    width: 76,
  },
  avatarLabel: {
    color: '#2b4e83',
    fontSize: 12,
    fontWeight: '700',
  },
  cancelButton: {
    alignItems: 'center',
    backgroundColor: '#eef3fb',
    borderColor: '#d7e1f1',
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 14,
  },
  cancelLabel: {
    color: '#2a466e',
    fontSize: 12,
    fontWeight: '700',
  },
  card: {
    backgroundColor: '#ffffff',
    borderColor: '#d6e3f3',
    borderRadius: 16,
    borderWidth: 1,
    maxHeight: '90%',
    maxWidth: 560,
    padding: 16,
    width: '100%',
  },
  error: {
    color: '#b42318',
    fontSize: 12,
    fontWeight: '700',
  },
  field: {
    gap: 4,
  },
  fieldError: {
    color: '#b42318',
    fontSize: 12,
    fontWeight: '700',
  },
  form: {
    gap: 8,
  },
  input: {
    backgroundColor: '#f6f9ff',
    borderColor: '#d4e0ef',
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  inputReadonly: {
    backgroundColor: '#ecf1f8',
    color: '#6b7b90',
  },
  inputError: {
    borderColor: '#d92d20',
  },
  label: {
    color: '#5e7088',
    fontSize: 12,
    fontWeight: '700',
  },
  overlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(9, 16, 28, 0.45)',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  resetBox: {
    backgroundColor: '#f2fff4',
    borderColor: '#bfe6c4',
    borderRadius: 12,
    borderWidth: 1,
    marginTop: 8,
    padding: 10,
  },
  resetButton: {
    alignItems: 'center',
    backgroundColor: '#16a34a',
    borderRadius: 10,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 14,
  },
  resetLabel: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
  },
  resetPasswordValue: {
    color: '#14532d',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 8,
  },
  resetText: {
    color: '#17653a',
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    marginRight: 10,
  },
  saveButton: {
    alignItems: 'center',
    backgroundColor: '#1c74e9',
    borderRadius: 10,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 14,
  },
  saveLabel: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
  },
  scroll: {
    marginTop: 10,
  },
  sectionRow: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  subtitle: {
    color: '#64748b',
    fontSize: 13,
  },
  title: {
    color: '#111418',
    fontSize: 20,
    fontWeight: '800',
  },
  textArea: {
    minHeight: 72,
    textAlignVertical: 'top',
  },
});

export const selectStyle: CSSProperties = {
  backgroundColor: '#f6f9ff',
  border: '1px solid #d4e0ef',
  borderRadius: 10,
  boxSizing: 'border-box',
  color: '#1b2434',
  minHeight: 38,
  outline: 'none',
  padding: '8px 12px',
  paddingRight: 28,
  width: '100%',
};
