import { StyleSheet } from 'react-native';
import { LIGHT } from '../../theme/light';

export const s = StyleSheet.create({
  avatarPlaceholder: {
    alignItems: 'center',
    backgroundColor: LIGHT.accentSoft,
    justifyContent: 'center',
  },
  backBtn: {
    alignItems: 'center',
    backgroundColor: LIGHT.bgCard,
    borderColor: LIGHT.border,
    borderRadius: LIGHT.radiusFull,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  backIcon: { color: LIGHT.text, fontSize: 20, fontWeight: '700' },
  centered: { alignItems: 'center', flex: 1, justifyContent: 'center' },
  chip: {
    backgroundColor: LIGHT.accentSoft,
    borderColor: LIGHT.borderStrong,
    borderRadius: LIGHT.radiusFull,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chipText: { color: LIGHT.accentDark, fontSize: 12, fontWeight: '600' },
  closeBtn: {
    alignItems: 'center',
    backgroundColor: LIGHT.accentSoft,
    borderRadius: LIGHT.radiusFull,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  closeBtnText: { color: LIGHT.textMuted, fontSize: 18 },
  dayBadge: {
    alignItems: 'center',
    backgroundColor: LIGHT.accentSoft,
    borderRadius: LIGHT.radiusSm,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  dayBadgeText: { color: LIGHT.accentDark, fontSize: 15, fontWeight: '900' },
  dayCard: {
    alignItems: 'center',
    backgroundColor: LIGHT.bgCard,
    borderColor: LIGHT.border,
    borderRadius: LIGHT.radiusXl,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    padding: 16,
  },
  dayCardActive: {
    borderColor: LIGHT.accent,
    borderWidth: 2,
  },
  dayChevron: { color: LIGHT.accentMuted, fontSize: 22, fontWeight: '300' },
  dayExCount: { color: LIGHT.textMuted, fontSize: 12 },
  dayExPill: {
    backgroundColor: LIGHT.accentSoft,
    borderRadius: LIGHT.radiusFull,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  dayExPillText: { color: LIGHT.accentDark, fontSize: 12, fontWeight: '700' },
  dayInfo: { flex: 1, gap: 2 },
  dayName: { color: LIGHT.textStrong, fontSize: 16, fontWeight: '700' },
  dayNotesCard: {
    backgroundColor: LIGHT.bgSoft,
    borderColor: LIGHT.border,
    borderRadius: LIGHT.radiusMd,
    borderWidth: 1,
    gap: 8,
    padding: 16,
  },
  detailLabel: {
    color: LIGHT.accentMuted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  detailRow: { gap: 2, width: '48%' },
  detailUnit: { color: LIGHT.textMuted, fontSize: 12 },
  detailValue: { color: LIGHT.textStrong, fontSize: 16, fontWeight: '800' },
  detailedGrid: {
    backgroundColor: LIGHT.bgCard,
    borderColor: LIGHT.border,
    borderRadius: LIGHT.radiusLg,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    padding: 20,
  },
  emptyText: { color: LIGHT.textMuted, fontSize: 14 },
  exMetaItem: { alignItems: 'center', gap: 2 },
  exMetaLabel: {
    color: LIGHT.accentMuted,
    fontSize: 9,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  exMetaValue: { color: LIGHT.textStrong, fontSize: 16, fontWeight: '800' },
  exerciseBody: { gap: 10, paddingTop: 10 },
  exerciseCard: {
    backgroundColor: LIGHT.bgCard,
    borderColor: LIGHT.border,
    borderRadius: LIGHT.radiusXl,
    borderWidth: 1,
    padding: 16,
  },
  exerciseChevron: { color: LIGHT.accent, fontSize: 14 },
  exerciseCount: { color: LIGHT.textMuted, fontSize: 13, fontWeight: '600' },
  exerciseHeader: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  exerciseName: { color: LIGHT.textStrong, flex: 1, fontSize: 16, fontWeight: '700' },
  exerciseNotes: { color: LIGHT.textMuted, fontSize: 12, fontStyle: 'italic', lineHeight: 18 },
  exerciseMetaRow: { flexDirection: 'row', gap: 16, justifyContent: 'flex-start' },
  exerciseTypeBadge: { borderRadius: 6, paddingHorizontal: 8, paddingVertical: 2 },
  exerciseTypeText: { fontSize: 10, fontWeight: '800' },
  fieldCard: {
    backgroundColor: LIGHT.bgCard,
    borderColor: LIGHT.border,
    borderRadius: LIGHT.radiusMd,
    borderWidth: 1,
    gap: 2,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  fieldLabel: {
    color: LIGHT.accentMuted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  fieldValue: { color: LIGHT.textStrong, fontSize: 14, fontWeight: '700' },
  finishDayBanner: {
    alignItems: 'center',
    backgroundColor: LIGHT.emeraldSoft,
    borderRadius: LIGHT.radiusMd,
    marginTop: 16,
    paddingVertical: 16,
  },
  finishDayText: { color: LIGHT.success, fontSize: 16, fontWeight: '800' },
  fullOverlay: {
    backgroundColor: LIGHT.bgSoft,
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 50,
  },
  goalBadge: {
    alignSelf: 'flex-start',
    backgroundColor: LIGHT.emeraldSoft,
    borderRadius: LIGHT.radiusSm,
    marginTop: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  goalBadgeText: { color: LIGHT.success, fontSize: 10, fontWeight: '800' },
  heroAvatarWrap: {
    borderColor: LIGHT.borderStrong,
    borderRadius: LIGHT.radiusFull,
    borderWidth: 2,
    overflow: 'hidden',
  },
  heroInfo: { flex: 1 },
  heroName: { color: LIGHT.textStrong, fontSize: 20, fontWeight: '800' },
  heroStatusDot: {
    backgroundColor: LIGHT.emerald,
    borderRadius: LIGHT.radiusFull,
    height: 8,
    width: 8,
  },
  heroStatusRow: { alignItems: 'center', flexDirection: 'row', gap: 6, marginTop: 4 },
  heroStatusText: { color: LIGHT.success, fontSize: 12, fontWeight: '600' },
  homeContent: { flex: 1, gap: 16, paddingBottom: 100, paddingHorizontal: 24, paddingTop: 8 },
  homeHeader: { flexDirection: 'row', gap: 16, paddingHorizontal: 24, paddingTop: 32 },
  homeScroll: { flex: 1 },
  levelLabel: {
    color: LIGHT.accentMuted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  levelRow: { flexDirection: 'row', gap: 8, justifyContent: 'space-between' },
  levelValue: { color: LIGHT.textStrong, fontSize: 14, fontWeight: '700' },
  logoutBtn: {
    alignItems: 'center',
    borderColor: LIGHT.borderStrong,
    borderRadius: LIGHT.radiusSm,
    borderWidth: 1,
    marginTop: 8,
    paddingVertical: 14,
  },
  logoutBtnText: { color: LIGHT.textMuted, fontSize: 14, fontWeight: '700' },
  medicalDot: { borderRadius: LIGHT.radiusFull, height: 10, marginTop: 4, width: 10 },
  medicalInfo: { flex: 1, gap: 2 },
  medicalLabel: { color: LIGHT.textStrong, fontSize: 13, fontWeight: '700' },
  medicalRow: {
    borderBottomColor: LIGHT.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingBottom: 12,
    paddingTop: 4,
  },
  medicalValue: { color: LIGHT.textMuted, fontSize: 12, lineHeight: 18 },
  metricCard: {
    alignItems: 'center',
    backgroundColor: LIGHT.bgCard,
    borderColor: LIGHT.border,
    borderRadius: LIGHT.radiusMd,
    borderWidth: 1,
    flex: 1,
    gap: 4,
    paddingVertical: 14,
  },
  metricCardLabel: {
    color: LIGHT.accentMuted,
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  metricCardUnit: { color: LIGHT.textMuted, fontSize: 12, fontWeight: '500' },
  metricCardValue: { color: LIGHT.textStrong, fontSize: 20, fontWeight: '900' },
  metricsRow: { flexDirection: 'row', gap: 10 },
  moreHeader: {
    backgroundColor: LIGHT.bg,
    borderBottomColor: LIGHT.border,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    borderBottomWidth: 1,
    paddingBottom: 24,
    paddingHorizontal: 24,
    paddingTop: 40,
  },
  moreHeaderSub: { color: LIGHT.accent, fontSize: 14, fontWeight: '500' },
  moreHeaderTitle: { color: LIGHT.textStrong, fontSize: 28, fontWeight: '800', marginBottom: 8 },
  moreItem: {
    alignItems: 'center',
    backgroundColor: LIGHT.bgCard,
    borderColor: LIGHT.border,
    borderRadius: LIGHT.radiusXl,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
  },
  moreItemIcon: {
    alignItems: 'center',
    backgroundColor: LIGHT.accentSoft,
    borderRadius: LIGHT.radiusMd,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  moreItemLabel: { color: LIGHT.text, fontSize: 17, fontWeight: '700' },
  moreItemLeft: { alignItems: 'center', flexDirection: 'row', gap: 16 },
  moreList: { gap: 12, padding: 24, paddingBottom: 100 },
  notesCard: {
    backgroundColor: LIGHT.bgSoft,
    borderColor: LIGHT.border,
    borderLeftColor: LIGHT.accent,
    borderLeftWidth: 3,
    borderRadius: LIGHT.radiusMd,
    borderWidth: 1,
    gap: 8,
    padding: 16,
  },
  notesText: { color: LIGHT.text, fontSize: 14, lineHeight: 22 },
  objectivePill: {
    alignSelf: 'flex-start',
    backgroundColor: LIGHT.bgSoft,
    borderColor: LIGHT.borderStrong,
    borderRadius: LIGHT.radiusSm,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  objectivePillText: { color: LIGHT.textStrong, fontSize: 14, fontWeight: '600' },
  overlayHeader: {
    alignItems: 'center',
    backgroundColor: LIGHT.bgCard,
    borderBottomColor: LIGHT.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  overlayTitle: { color: LIGHT.textStrong, flex: 1, fontSize: 18, fontWeight: '800' },
  panelContent: { gap: 16, padding: 20, paddingBottom: 40 },
  photoBtn: {
    alignItems: 'center',
    backgroundColor: LIGHT.bgCard,
    borderColor: LIGHT.border,
    borderRadius: LIGHT.radiusXl,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 120,
    padding: 16,
  },
  photoBtnText: { color: LIGHT.text, fontSize: 14, fontWeight: '600', marginTop: 8 },
  photoThumb: {
    borderColor: LIGHT.borderStrong,
    borderRadius: LIGHT.radiusSm,
    borderWidth: 1,
    height: 80,
    width: 80,
  },
  photosRow: { gap: 10 },
  profileCard: {
    backgroundColor: LIGHT.bgCard,
    borderColor: LIGHT.border,
    borderRadius: LIGHT.radiusXl,
    flex: 1,
    justifyContent: 'center',
    padding: 16,
  },
  profileCardAvatar: {
    alignItems: 'center',
    backgroundColor: LIGHT.accentSoft,
    borderRadius: LIGHT.radiusFull,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  profileCardInfo: { flex: 1 },
  profileCardLabel: {
    color: LIGHT.accentMuted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  profileCardName: { color: LIGHT.textStrong, fontSize: 14, fontWeight: '600' },
  profileCardRow: { alignItems: 'center', flexDirection: 'row', gap: 12 },
  profileHero: { alignItems: 'center', flexDirection: 'row', gap: 16 },
  profileStatCol: { alignItems: 'center' },
  profileStatLabel: {
    color: LIGHT.accentMuted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginTop: 2,
    textTransform: 'uppercase',
  },
  profileStatValue: { color: LIGHT.textStrong, fontSize: 16, fontWeight: '800' },
  profileStatsRow: { alignItems: 'center', flexDirection: 'row', gap: 16 },
  root: {
    backgroundColor: LIGHT.bgSoft,
    flex: 1,
    overflow: 'hidden',
  },
  routineChip: {
    backgroundColor: LIGHT.accentSoft,
    borderColor: LIGHT.borderStrong,
    borderRadius: LIGHT.radiusFull,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  routineChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  routineChipText: { color: LIGHT.accentDark, fontSize: 11, fontWeight: '600' },
  routineHero: {
    backgroundColor: LIGHT.bgCard,
    borderColor: LIGHT.border,
    borderRadius: LIGHT.radiusXl,
    borderWidth: 1,
    gap: 8,
    padding: 20,
    position: 'relative',
  },
  routineHeroLabel: {
    color: LIGHT.accentMuted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  routineHeroMeta: { bottom: 20, position: 'absolute', right: 20 },
  routineHeroName: { color: LIGHT.textStrong, fontSize: 22, fontWeight: '900' },
  routineHeroSub: { color: LIGHT.textMuted, fontSize: 14, fontWeight: '500' },
  routineSectionLabel: {
    color: LIGHT.accent,
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginBottom: 12,
    marginLeft: 8,
    textTransform: 'uppercase',
  },
  routineSeparator: {
    backgroundColor: LIGHT.borderStrong,
    height: 1,
    marginBottom: 24,
    marginTop: 8,
    opacity: 0.5,
  },
  sectionCard: {
    backgroundColor: LIGHT.bgCard,
    borderColor: LIGHT.border,
    borderRadius: LIGHT.radiusLg,
    borderWidth: 1,
    gap: 12,
    padding: 16,
  },
  sectionLabel: {
    color: LIGHT.accentMuted,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  sidePanel: { backgroundColor: LIGHT.bgSoft, flex: 1 },
  startTrainingBtn: {
    alignItems: 'center',
    backgroundColor: LIGHT.emeraldBg,
    borderRadius: LIGHT.radiusMd,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 16,
    width: '100%',
  },
  startTrainingBtnLabel: { color: LIGHT.textOnNavy, fontSize: 15, fontWeight: '800' },
  startTrainingError: { color: LIGHT.error, fontSize: 13, textAlign: 'center' },
  statGrid: { flexDirection: 'row', gap: 12 },
  todayCard: {
    backgroundColor: LIGHT.bgNavy,
    borderColor: LIGHT.bgNavySoft,
    borderRadius: LIGHT.radiusXl,
    flex: 1,
    justifyContent: 'center',
    padding: 16,
  },
  todayCardDate: { color: LIGHT.textOnNavyMuted, fontSize: 12, fontWeight: '500' },
  todayCardFocus: { color: LIGHT.textOnNavy, fontSize: 18, fontWeight: '800', lineHeight: 22 },
  todayCardHeader: { alignItems: 'flex-start', flexDirection: 'row', justifyContent: 'space-between' },
  workoutTimer: {
    alignItems: 'center',
    backgroundColor: LIGHT.emeraldSoft,
    borderColor: LIGHT.emerald,
    borderRadius: LIGHT.radiusMd,
    borderWidth: 1,
    flexDirection: 'row',
    fontFamily: 'monospace',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  workoutTimerDot: {
    backgroundColor: LIGHT.emerald,
    borderRadius: LIGHT.radiusFull,
    height: 8,
    width: 8,
  },
  workoutTimerText: { color: LIGHT.success, fontSize: 14, fontWeight: '800' },
});
