import { StyleSheet } from 'react-native';
import { DARK } from '../dark';

export const s = StyleSheet.create({
  avatarPlaceholder: {
    alignItems: 'center',
    backgroundColor: '#2d1060',
    justifyContent: 'center',
  },
  backBtn: {
    alignItems: 'center',
    backgroundColor: 'rgba(109,40,217,0.3)',
    borderRadius: 99,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  backIcon: { color: '#c4b5fd', fontSize: 22 },
  bar: {
    alignItems: 'flex-start',
    backgroundColor: 'rgba(0,0,0,0.85)',
    borderTopColor: 'rgba(88,28,135,0.5)',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingBottom: 28,
    paddingHorizontal: 4,
    paddingTop: 16,
  },
  barEmoji: { fontSize: 22 },
  barIconWrap: {
    alignItems: 'center',
    backgroundColor: 'rgba(109,40,217,0.15)',
    borderColor: 'rgba(139,92,246,0.25)',
    borderRadius: 14,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  barItem: { alignItems: 'center', gap: 4, width: 72 },
  barLabel: { color: 'rgba(196,181,253,0.7)', fontSize: 9, fontWeight: '600', textAlign: 'center' },
  centered: { alignItems: 'center', flex: 1, justifyContent: 'center' },
  centerAvatar: {
    alignItems: 'center',
    backgroundColor: '#000',
    borderColor: DARK.accent,
    borderRadius: 999,
    borderWidth: 3,
    height: 156,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 156,
  },
  chevronBtn: {
    alignSelf: 'center',
    backgroundColor: 'rgba(0,0,0,0.8)',
    borderColor: 'rgba(88,28,135,0.5)',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderWidth: 1,
    borderBottomWidth: 0,
    paddingHorizontal: 28,
    paddingVertical: 4,
  },
  chevronIcon: { color: '#a78bfa', fontSize: 18, fontWeight: '700' },
  chevronRow: { alignItems: 'center', marginBottom: -1 },
  chip: {
    backgroundColor: 'rgba(109,40,217,0.2)',
    borderColor: 'rgba(139,92,246,0.3)',
    borderRadius: 99,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chipText: { color: '#c4b5fd', fontSize: 12, fontWeight: '600' },
  circle: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderColor: 'rgba(139,92,246,0.3)',
    borderRadius: 999,
    borderWidth: 1,
    gap: 2,
    height: 76,
    justifyContent: 'center',
    position: 'absolute',
    width: 76,
  },
  circleBottomLeft: { bottom: '14%', left: '8%' },
  circleBottomRight: { bottom: '14%', right: '8%' },
  circleEmoji: { fontSize: 22 },
  circleLabel: { color: DARK.accent, fontSize: 9, fontWeight: '800', letterSpacing: 0.5 },
  circleTopLeft: { left: '8%', top: '14%' },
  circleTopRight: { right: '8%', top: '14%' },
  closeBtn: {
    alignItems: 'center',
    backgroundColor: 'rgba(109,40,217,0.3)',
    borderRadius: 99,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  closeBtnText: { color: '#c4b5fd', fontSize: 18 },
  dayBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(236,72,153,0.15)',
    borderRadius: 12,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  dayBadgeText: { color: DARK.accent, fontSize: 15, fontWeight: '900' },
  dayCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.4)',
    borderColor: 'rgba(139,92,246,0.2)',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    padding: 16,
  },
  dayChevron: { color: '#a78bfa', fontSize: 22, fontWeight: '300' },
  dayExCount: { color: DARK.textMuted, fontSize: 12 },
  dayInfo: { flex: 1, gap: 2 },
  dayName: { color: '#fff', fontSize: 16, fontWeight: '700' },
  dayNotesCard: {
    backgroundColor: 'rgba(109,40,217,0.1)',
    borderColor: 'rgba(139,92,246,0.2)',
    borderRadius: 16,
    borderWidth: 1,
    gap: 8,
    padding: 16,
  },
  detailLabel: { fontSize: 10, fontWeight: '700', letterSpacing: 1, textTransform: 'uppercase' },
  detailRow: { gap: 2, width: '48%' },
  detailUnit: { color: DARK.textMuted, fontSize: 12 },
  detailValue: { fontSize: 16, fontWeight: '800' },
  detailedGrid: {
    backgroundColor: 'rgba(109,40,217,0.1)',
    borderColor: 'rgba(139,92,246,0.2)',
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    padding: 20,
  },
  emptyText: { color: DARK.textMuted, fontSize: 14 },
  exMetaItem: { alignItems: 'center', gap: 2 },
  exMetaLabel: { color: DARK.textMuted, fontSize: 9, fontWeight: '700', textTransform: 'uppercase' },
  exMetaValue: { color: '#fff', fontSize: 16, fontWeight: '800' },
  exerciseBody: { gap: 10, paddingTop: 10 },
  exerciseCard: {
    backgroundColor: 'rgba(0,0,0,0.4)',
    borderColor: 'rgba(139,92,246,0.2)',
    borderRadius: 16,
    borderWidth: 1,
    padding: 14,
  },
  exerciseChevron: { color: '#a78bfa', fontSize: 14 },
  exerciseCount: { color: DARK.textMuted, fontSize: 13, fontWeight: '600' },
  exerciseHeader: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  exerciseName: { color: '#fff', flex: 1, fontSize: 14, fontWeight: '700' },
  exerciseNotes: { color: DARK.textMuted, fontSize: 12, fontStyle: 'italic', lineHeight: 18 },
  exerciseMetaRow: { flexDirection: 'row', gap: 16, justifyContent: 'flex-start' },
  exerciseTypeBadge: { borderRadius: 6, paddingHorizontal: 8, paddingVertical: 2 },
  exerciseTypeText: { fontSize: 10, fontWeight: '800' },
  fullOverlay: {
    backgroundColor: '#07000f',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 50,
  },
  glowBlue: {
    backgroundColor: 'rgba(59,130,246,0.08)',
    borderRadius: 9999,
    bottom: 60,
    height: 400,
    position: 'absolute',
    right: -120,
    width: 350,
  },
  glowPink: {
    backgroundColor: 'rgba(236,72,153,0.1)',
    borderRadius: 9999,
    height: 350,
    left: -120,
    position: 'absolute',
    top: -150,
    width: 420,
  },
  goalBadge: {
    alignSelf: 'flex-start',
    backgroundColor: DARK.accent,
    borderRadius: 99,
    marginTop: 6,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  goalBadgeText: { color: '#000', fontSize: 10, fontWeight: '900' },
  heroAvatarWrap: {
    borderColor: DARK.accent,
    borderRadius: 999,
    borderWidth: 2,
    overflow: 'hidden',
  },
  heroInfo: { flex: 1 },
  heroName: { color: '#fff', fontSize: 24, fontWeight: '900' },
  heroStatusDot: {
    backgroundColor: '#4ade80',
    borderRadius: 99,
    height: 8,
    width: 8,
  },
  heroStatusRow: { alignItems: 'center', flexDirection: 'row', gap: 6, marginTop: 4 },
  heroStatusText: { color: '#4ade80', fontSize: 12, fontWeight: '600' },
  hub: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    position: 'relative',
  },
  hubWrapper: { flex: 1 },
  levelLabel: { color: DARK.textMuted, fontSize: 10, fontWeight: '700', letterSpacing: 1, textTransform: 'uppercase' },
  levelRow: { flexDirection: 'row', gap: 8, justifyContent: 'space-between' },
  levelValue: { color: '#fff', fontSize: 14, fontWeight: '700' },
  logoutBtn: {
    alignItems: 'center',
    borderColor: 'rgba(139,92,246,0.3)',
    borderRadius: 12,
    borderWidth: 1,
    marginTop: 8,
    paddingVertical: 14,
  },
  logoutBtnText: { color: DARK.textMuted, fontSize: 14, fontWeight: '700' },
  medicalDot: { borderRadius: 99, height: 10, marginTop: 4, width: 10 },
  medicalInfo: { flex: 1, gap: 2 },
  medicalLabel: { color: '#fff', fontSize: 13, fontWeight: '700' },
  medicalRow: {
    borderBottomColor: 'rgba(139,92,246,0.15)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingBottom: 12,
    paddingTop: 4,
  },
  medicalValue: { color: DARK.textMuted, fontSize: 12, lineHeight: 18 },
  menuActiveBox: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderColor: 'rgba(88,28,135,0.3)',
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
    minHeight: 110,
    padding: 14,
    paddingTop: 16,
  },
  menuActiveEmoji: { fontSize: 22 },
  menuActiveIcon: {
    alignItems: 'center',
    backgroundColor: DARK.accent,
    borderRadius: 14,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  menuActiveItem: { alignItems: 'center', gap: 4, width: 64 },
  menuActiveLabel: { color: DARK.accent, fontSize: 9, fontWeight: '700', textAlign: 'center' },
  menuContent: { gap: 20, padding: 20, paddingBottom: 60 },
  menuCounter: { color: '#a78bfa', fontSize: 12, fontWeight: '800' },
  menuCounterFull: { color: DARK.accent },
  menuEmptyText: { color: 'rgba(109,40,217,0.5)', fontSize: 13, fontWeight: '500', textAlign: 'center', width: '100%' },
  menuGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    justifyContent: 'flex-start',
  },
  menuGridEmoji: { fontSize: 22 },
  menuGridIcon: {
    alignItems: 'center',
    borderColor: 'rgba(139,92,246,0.25)',
    borderRadius: 14,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  menuGridItem: { alignItems: 'center', gap: 4, width: 72 },
  menuGridLabel: { color: '#a78bfa', fontSize: 9, fontWeight: '600', textAlign: 'center' },
  menuHeader: {
    alignItems: 'center',
    borderBottomColor: 'rgba(88,28,135,0.3)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 40,
    paddingBottom: 16,
  },
  menuPanel: { backgroundColor: 'rgba(0,0,0,0.97)', flex: 1 },
  menuScroll: { flex: 1 },
  menuSectionHeader: { flexDirection: 'row', justifyContent: 'space-between' },
  menuSectionLabel: { color: '#a78bfa', fontSize: 11, fontWeight: '800', letterSpacing: 1.5 },
  menuTitle: { color: '#fff', fontSize: 20, fontWeight: '800' },
  metricCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(109,40,217,0.2)',
    borderColor: 'rgba(139,92,246,0.2)',
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    gap: 4,
    paddingVertical: 14,
  },
  metricCardLabel: { color: DARK.textMuted, fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },
  metricCardUnit: { color: DARK.textMuted, fontSize: 12, fontWeight: '500' },
  metricCardValue: { color: '#fff', fontSize: 20, fontWeight: '900' },
  metricsRow: { flexDirection: 'row', gap: 10 },
  notesCard: {
    backgroundColor: 'rgba(109,40,217,0.1)',
    borderColor: 'rgba(139,92,246,0.2)',
    borderLeftColor: DARK.accent,
    borderLeftWidth: 3,
    borderRadius: 16,
    borderWidth: 1,
    gap: 8,
    padding: 16,
  },
  notesText: { color: '#e2e8f0', fontSize: 14, lineHeight: 22 },
  objectivePill: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderColor: 'rgba(139,92,246,0.4)',
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  objectivePillText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  overlayHeader: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.85)',
    borderBottomColor: 'rgba(88,28,135,0.5)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  overlayTitle: { color: '#fff', fontSize: 18, fontWeight: '800' },
  panelContent: { gap: 16, padding: 20, paddingBottom: 40 },
  photoThumb: { borderColor: 'rgba(139,92,246,0.3)', borderRadius: 12, borderWidth: 1, height: 80, width: 80 },
  photosRow: { gap: 10 },
  profileCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.4)',
    borderColor: 'rgba(139,92,246,0.2)',
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    margin: 16,
    marginTop: 36,
    padding: 14,
  },
  profileCardAvatar: {
    borderColor: DARK.accent,
    borderRadius: 999,
    borderWidth: 2,
    overflow: 'hidden',
  },
  profileCardInfo: { flex: 1 },
  profileCardName: { color: '#fff', fontSize: 18, fontWeight: '800' },
  profileCardSub: { color: '#c4b5fd', fontSize: 13, fontWeight: '500' },
  profileHero: { alignItems: 'center', flexDirection: 'row', gap: 16 },
  root: {
    backgroundColor: '#07000f',
    flex: 1,
    overflow: 'hidden',
  },
  routineChip: {
    backgroundColor: 'rgba(0,0,0,0.4)',
    borderColor: 'rgba(139,92,246,0.3)',
    borderRadius: 99,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  routineChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  routineChipText: { color: '#c4b5fd', fontSize: 11, fontWeight: '600' },
  routineHero: {
    backgroundColor: 'rgba(109,40,217,0.15)',
    borderColor: 'rgba(139,92,246,0.25)',
    borderRadius: 22,
    borderWidth: 1,
    gap: 8,
    padding: 20,
  },
  routineHeroLabel: {
    color: DARK.textMuted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  routineHeroName: { color: '#fff', fontSize: 22, fontWeight: '900' },
  sectionCard: {
    backgroundColor: 'rgba(109,40,217,0.1)',
    borderColor: 'rgba(139,92,246,0.2)',
    borderRadius: 20,
    borderWidth: 1,
    gap: 12,
    padding: 16,
  },
  sectionLabel: { color: '#a78bfa', fontSize: 10, fontWeight: '800', letterSpacing: 1.5, textTransform: 'uppercase' },
  sidePanel: { backgroundColor: '#07000f', flex: 1 },
});
