export type Client = {
  avatarUrl: null | string;
  birthDate: Date | null;
  coachMembershipId: string;
  createdAt: Date;
  email: string;
  fcMax: null | number;
  fcRest: null | number;
  firstName: string;
  fitnessLevel: null | string;
  heightCm: null | number;
  hipCm: null | number;
  id: string;
  injuries: null | string;
  lastName: string;
  notes: null | string;
  objective: string;
  objectiveId: string;
  organizationId: string;
  phone: null | string;
  secondaryObjectives: string[];
  sex: null | string;
  updatedAt: Date;
  waistCm: null | number;
  weightKg: null | number;
  allergies: null | string;
  trainingPlanId: string | null;
  trainingPlan?: { id: string; name: string };
};
