import { StyleSheet } from 'react-native';
import { LIGHT } from './light';

/** Shared light styles for session / overlay screens */
export const SESSION = StyleSheet.create({
  safeArea: { backgroundColor: LIGHT.bgSoft, flex: 1 },
  container: { backgroundColor: LIGHT.bgSoft, flex: 1 },
  header: {
    borderBottomColor: LIGHT.border,
    borderBottomWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  title: { color: LIGHT.textStrong, fontSize: 20, fontWeight: '800' },
  subtitle: { color: LIGHT.textMuted, fontSize: 14, marginTop: 4 },
  emptyText: { color: LIGHT.textMuted, fontSize: 16 },
  card: {
    backgroundColor: LIGHT.bgCard,
    borderColor: LIGHT.border,
    borderRadius: LIGHT.radiusXl,
    borderWidth: 1,
    padding: 16,
  },
  primaryBtn: {
    alignItems: 'center',
    backgroundColor: LIGHT.accent,
    borderRadius: LIGHT.radiusMd,
    paddingVertical: 14,
  },
  primaryBtnSuccess: { backgroundColor: LIGHT.emeraldBg },
  primaryBtnDanger: { backgroundColor: LIGHT.redBg },
  primaryBtnText: { color: LIGHT.textOnNavy, fontSize: 16, fontWeight: '700', textAlign: 'center' },
  secondaryBtn: {
    alignItems: 'center',
    backgroundColor: LIGHT.accentSoft,
    borderRadius: LIGHT.radiusMd,
    paddingVertical: 12,
  },
  secondaryBtnText: { color: LIGHT.accentDark, fontSize: 14, fontWeight: '600', textAlign: 'center' },
  input: {
    backgroundColor: LIGHT.bgSoft,
    borderColor: LIGHT.border,
    borderRadius: LIGHT.radiusSm,
    borderWidth: 1,
    color: LIGHT.textStrong,
    fontSize: 18,
    fontWeight: '700',
    padding: 12,
    textAlign: 'center',
  },
  inputLabel: {
    color: LIGHT.accentMuted,
    fontSize: 10,
    fontWeight: '700',
    marginBottom: 6,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  backBtn: {
    alignItems: 'center',
    backgroundColor: LIGHT.bgCard,
    borderColor: LIGHT.border,
    borderRadius: LIGHT.radiusFull,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  backArrow: { color: LIGHT.text, fontSize: 20, fontWeight: '700' },
  modalOverlay: {
    backgroundColor: LIGHT.bgSoft,
    flex: 1,
  },
  panel: {
    backgroundColor: LIGHT.bgCard,
    borderColor: LIGHT.border,
    borderRadius: LIGHT.radiusMd,
    borderWidth: 1,
    padding: 12,
  },
  label: { color: LIGHT.textMuted, fontSize: 12, fontWeight: '600' },
  value: { color: LIGHT.textStrong, fontSize: 16, fontWeight: '700' },
  error: { color: LIGHT.error, fontSize: 13, textAlign: 'center' },
  screenPadding: { padding: 16, paddingBottom: 40 },
});

export const SCREEN = StyleSheet.create({
  root: { backgroundColor: LIGHT.bgSoft, flex: 1 },
  header: {
    alignItems: 'center',
    backgroundColor: LIGHT.bgCard,
    borderBottomColor: LIGHT.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  headerTitle: { color: LIGHT.textStrong, flex: 1, fontSize: 18, fontWeight: '800' },
  content: { flex: 1, padding: 16 },
  card: {
    backgroundColor: LIGHT.bgCard,
    borderColor: LIGHT.border,
    borderRadius: LIGHT.radiusXl,
    borderWidth: 1,
    marginBottom: 12,
    padding: 16,
  },
  muted: { color: LIGHT.textMuted, fontSize: 14 },
  text: { color: LIGHT.textStrong, fontSize: 15 },
});
