import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  actions: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'flex-end',
    marginTop: 10,
  },
  userTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    width: '100%',
  },
  avatarWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#eff6ff',
    borderWidth: 2,
    borderColor: '#3b82f6',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  avatar: {
    width: '100%',
    height: '100%',
  },
  avatarEditor: {
    alignItems: 'center',
    gap: 8,
  },
  avatarLarge: {
    borderRadius: 999,
    height: 72,
    width: 72,
  },
  cancelButton: {
    alignItems: 'center',
    backgroundColor: '#edf3fb',
    borderColor: '#d6e2f2',
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 12,
  },
  cancelLabel: {
    color: '#38557f',
    fontSize: 12,
    fontWeight: '700',
  },
  card: {
    backgroundColor: '#f8fafc',
    borderColor: '#f1f5f9',
    borderRadius: 20,
    borderWidth: 1,
    padding: 20,
    width: '100%',
  },
  changeAvatarButton: {
    alignItems: 'center',
    backgroundColor: '#edf3fb',
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 30,
    paddingHorizontal: 12,
  },
  changeAvatarLabel: {
    color: '#1c3f74',
    fontSize: 12,
    fontWeight: '700',
  },
  email: {
    color: '#64748b',
    fontSize: 12,
  },
  fieldLabel: {
    color: '#3b4f70',
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 3,
  },
  fields: {
    gap: 9,
  },
  gearButton: {
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
    borderRadius: 8,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  gearIcon: {
    color: '#64748b',
    fontSize: 16,
  },
  info: {
    flex: 1,
    gap: 2,
  },
  input: {
    backgroundColor: '#f4f8ff',
    borderColor: '#d7e2f3',
    borderRadius: 9,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  inputReadonly: {
    backgroundColor: '#edf2f8',
    color: '#5f6f84',
  },
  modalCard: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    gap: 10,
    maxWidth: 420,
    padding: 16,
    width: '100%',
  },
  modalTitle: {
    color: '#111418',
    fontSize: 20,
    fontWeight: '800',
  },
  name: {
    color: '#1e293b',
    fontSize: 14,
    fontWeight: '700',
  },
  overlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(11, 17, 24, 0.45)',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  saveButton: {
    alignItems: 'center',
    backgroundColor: '#1c74e9',
    borderRadius: 10,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 12,
  },
  saveLabel: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
  },
});
